from __future__ import annotations

# ADR-0034: the "regenerable tier" -- a small, deterministic, allow-listed clean that frees real
# disk space (permanent delete, no Recycle Bin) for things that are provably regenerated by their
# owner: package-manager download caches (cleaned by the tool's OWN prune command), aged %TEMP%
# content, crash dumps, and caches of browsers that are not running right now.
#
# This is deliberately NOT a candidate/`apply_batch` code path. ADR-0023's safe-mode guarantees
# (Recycle-Bin-only, Tier-B-only, no blanket apply) are about the generic, scan-driven pipeline
# that can reach any file under a scan root; they are untouched and still proven by
# evals/test_safe_mode_gate.py. This module is a separate, closed-world path: it never accepts a
# path from a caller, never walks outside the roots listed in `plan_regenerable_clean`, and every
# delete re-checks containment + reparse-point + open-handle state at the moment of the delete.
import contextlib
import ctypes
import dataclasses
import functools
import getpass
import json
import os
import re
import shutil
import stat
import subprocess
import sys
import time
import uuid
from collections.abc import Callable, Sequence
from dataclasses import dataclass, field
from pathlib import Path
from typing import Literal

import structlog

from reclaim.app_paths import data_root
from reclaim.safety import first_matching_pattern, subtree_exclusion_match
from reclaim.safety_env import (
    assert_not_real_profile_under_pytest,
    refuse_real_side_effect_under_pytest,
)

logger = structlog.get_logger(__name__)

DEFAULT_AUDIT_LOG_PATH = data_root() / "data" / "regenerable_audit.jsonl"

# Same 7-day floor the TEMP detector already uses (config.min_temp_root_age_hours = 168): an
# in-progress installer's scratch files or a running app's temp state must never be swept.
DEFAULT_MIN_AGE_SECONDS = 7 * 24 * 3600.0

# ADR-0034 addendum "pytest temp": a `pytest-<N>` basetemp is regenerated by the next pytest run,
# but the shared `pytest-of-<user>` parent holds runs of EVERY project that user tests, so the
# category is opt-in (`[regenerable] pytest_temp`).
PYTEST_TEMP_MIN_AGE_SECONDS = 7 * 24 * 3600.0
# ASCII digits only (pytest never writes a Unicode digit); fullmatch so `pytest-current`,
# `pytest-5.bak` and `xpytest-5` are all ignored.
_PYTEST_BASETEMP_RE = re.compile(r"pytest-[0-9]+")
_PYTEST_ROOT_PREFIX = "pytest-of-"

# Any subtree containing one of these is somebody's parked project/environment, not litter: it is
# reported as skipped, never deleted (the hardlink-into-an-active-install incident class).
_GUARD_NAMES = frozenset({".git", ".venv", "venv", "pyvenv.cfg", "site-packages", "node_modules"})

_FILE_ATTRIBUTE_REPARSE_POINT = 0x400

# How long `uv cache prune` may WAIT for uv's own cache lock before the item is skipped. uv holds
# that lock precisely so a prune waits for in-flight installs instead of racing them, so waiting
# is the safe behaviour; skipping up front whenever any uv.exe runs meant the biggest cache was
# almost never cleaned on a workstation with several agent sessions (ADR-0034, limit 1). 30 min:
# long enough to outlast typical agent-session installs, short enough that the run is bounded.
UV_LOCK_WAIT_SECONDS = 1800.0
# The subprocess timeout is the lock wait plus this margin, so uv's own "Timeout ... waiting for
# lock" error (a clean, reportable exit) normally fires before the hard kill does.
_LOCK_WAIT_KILL_MARGIN_SECONDS = 60.0

ItemKind = Literal["native_command", "aged_temp", "crash_dump", "browser_cache", "pytest_temp"]
# "off": the category is not planned at all. "report": dry-run only (listed, never deleted, even
# if `apply` is set). "delete": listed and, on apply, deleted (the `[regenerable] pytest_temp =
# true` opt-in).
PytestTempMode = Literal["off", "report", "delete"]
ItemStatus = Literal[
    "cleaned",
    "nothing_to_clean",
    "would_clean",
    "skipped_not_present",
    "skipped_in_use",
    "skipped_browser_running",
    "skipped_tool_missing",
    "skipped_no_access",
    "skipped_excluded",
    "failed",
]


@dataclass(frozen=True, slots=True)
class CommandResult:
    returncode: int
    stdout: str
    stderr: str
    timed_out: bool = False


@dataclass(frozen=True, slots=True)
class NativeToolSpec:
    """One package manager's own cache-clean command. `busy_process_names` are the tool's own
    executables: if any is running, the tool may hold its cache lock or be mid-install, so the
    whole item is skipped (never `--force`d past a lock) -- UNLESS `own_lock` is set: the tool
    then guards its cache with a real lock that makes the command WAIT (bounded, see
    `UV_LOCK_WAIT_SECONDS`) instead of racing, so a running process is not a reason to skip."""

    key: str
    label: str
    executable: str
    argv_tail: tuple[str, ...]
    cache_root_relative_to: Literal["local_appdata", "home"]
    cache_root_tail: str
    busy_process_names: frozenset[str]
    own_lock: bool = False


# Allow-list. Each command only removes the tool's regenerable download/index cache -- never an
# installed environment. `uv cache prune` removes only unreferenced entries (never `uv cache
# clean`); conda is limited to tarballs + index cache (never `--packages`/`--all`, which can
# remove package dirs hardlinked into live environments).
NATIVE_TOOLS: tuple[NativeToolSpec, ...] = (
    NativeToolSpec(
        "uv",
        "uv package cache",
        "uv",
        ("cache", "prune"),
        "local_appdata",
        "uv/cache",
        frozenset({"uv.exe", "uvx.exe"}),
        # Measured (uv 0.11.14, scratch cache dir): with its `.lock` held elsewhere, `uv cache
        # prune` waits and then exits 2 with "Timeout (Ns) when waiting for lock on ...".
        own_lock=True,
    ),
    NativeToolSpec(
        "pip",
        "pip download cache",
        "pip",
        ("cache", "purge"),
        "local_appdata",
        "pip/Cache",
        frozenset({"pip.exe", "pip3.exe"}),
    ),
    NativeToolSpec(
        "npm",
        "npm download cache",
        "npm",
        ("cache", "clean", "--force"),
        "local_appdata",
        "npm-cache",
        frozenset(),
    ),
    NativeToolSpec(
        "conda",
        "conda tarball/index cache",
        "conda",
        ("clean", "--tarballs", "--index-cache", "-y"),
        "home",
        ".conda/pkgs",
        frozenset({"conda.exe"}),
    ),
    NativeToolSpec(
        "yarn",
        "yarn download cache",
        "yarn",
        ("cache", "clean"),
        "local_appdata",
        "Yarn/Cache",
        frozenset({"yarn.exe"}),
    ),
)


@dataclass(frozen=True, slots=True)
class BrowserSpec:
    key: str
    label: str
    process_names: frozenset[str]
    # Relative to %LOCALAPPDATA%. "*" in a path component matches one directory level.
    profile_roots: tuple[str, ...]
    cache_dir_names: tuple[str, ...]


# Only disk caches: never Cookies, Local Storage, History, Login Data or extensions. msedgewebview2
# is deliberately NOT in Edge's process set -- it is a shared runtime other apps embed.
BROWSERS: tuple[BrowserSpec, ...] = (
    BrowserSpec(
        "chrome",
        "Google Chrome",
        frozenset({"chrome.exe"}),
        ("Google/Chrome/User Data",),
        ("Cache", "Code Cache", "GPUCache"),
    ),
    BrowserSpec(
        "edge",
        "Microsoft Edge",
        frozenset({"msedge.exe"}),
        ("Microsoft/Edge/User Data",),
        ("Cache", "Code Cache", "GPUCache"),
    ),
    BrowserSpec(
        "brave",
        "Brave",
        frozenset({"brave.exe"}),
        ("BraveSoftware/Brave-Browser/User Data",),
        ("Cache", "Code Cache", "GPUCache"),
    ),
    BrowserSpec(
        "firefox",
        "Mozilla Firefox",
        frozenset({"firefox.exe"}),
        ("Mozilla/Firefox/Profiles",),
        ("cache2",),
    ),
)

# Chromium keeps profile data in "Default" and "Profile N"; Firefox in randomly named dirs.
_CHROMIUM_PROFILE_PREFIXES = ("Default", "Profile ", "Guest Profile")


# --- Environment (injectable so tests never touch the real machine) ---------------------------


def _real_running_process_names() -> frozenset[str]:
    """Lower-cased image names of every running process, via the Toolhelp snapshot API (no
    subprocess). Raises on failure so the caller fails CLOSED (treats every browser/tool as
    running) rather than silently reporting an empty process list."""
    if sys.platform != "win32":
        raise OSError("process enumeration is Windows-only")
    import ctypes.wintypes as wt

    class PROCESSENTRY32W(ctypes.Structure):
        _fields_ = (
            ("dwSize", wt.DWORD),
            ("cntUsage", wt.DWORD),
            ("th32ProcessID", wt.DWORD),
            ("th32DefaultHeapID", ctypes.c_size_t),
            ("th32ModuleID", wt.DWORD),
            ("cntThreads", wt.DWORD),
            ("th32ParentProcessID", wt.DWORD),
            ("pcPriClassBase", wt.LONG),
            ("dwFlags", wt.DWORD),
            ("szExeFile", wt.WCHAR * 260),
        )

    kernel32 = ctypes.WinDLL("kernel32", use_last_error=True)
    kernel32.CreateToolhelp32Snapshot.restype = wt.HANDLE
    kernel32.CreateToolhelp32Snapshot.argtypes = (wt.DWORD, wt.DWORD)
    kernel32.Process32FirstW.argtypes = (wt.HANDLE, ctypes.POINTER(PROCESSENTRY32W))
    kernel32.Process32NextW.argtypes = (wt.HANDLE, ctypes.POINTER(PROCESSENTRY32W))
    kernel32.CloseHandle.argtypes = (wt.HANDLE,)
    th32cs_snapprocess = 0x2
    snapshot = kernel32.CreateToolhelp32Snapshot(th32cs_snapprocess, 0)
    if snapshot in (None, wt.HANDLE(-1).value):
        raise OSError(f"CreateToolhelp32Snapshot failed: {ctypes.get_last_error()}")
    names: set[str] = set()
    try:
        entry = PROCESSENTRY32W()
        entry.dwSize = ctypes.sizeof(PROCESSENTRY32W)
        ok = kernel32.Process32FirstW(snapshot, ctypes.byref(entry))
        while ok:
            names.add(entry.szExeFile.lower())
            ok = kernel32.Process32NextW(snapshot, ctypes.byref(entry))
    finally:
        kernel32.CloseHandle(snapshot)
    return frozenset(names)


def file_has_open_handle(path: str) -> bool:
    """True if ANY other handle is open on `path` (or it cannot be probed). Opens with share
    mode 0, which Windows refuses (sharing violation) while any other handle exists, regardless
    of that handle's own sharing flags. Fail-closed: every error except 'file already gone'
    counts as in-use, so an unknown state never reads as deletable."""
    if sys.platform != "win32":
        return True
    import ctypes.wintypes as wt

    kernel32 = ctypes.WinDLL("kernel32", use_last_error=True)
    kernel32.CreateFileW.restype = wt.HANDLE
    kernel32.CreateFileW.argtypes = (
        wt.LPCWSTR,
        wt.DWORD,
        wt.DWORD,
        wt.LPVOID,
        wt.DWORD,
        wt.DWORD,
        wt.HANDLE,
    )
    kernel32.CloseHandle.argtypes = (wt.HANDLE,)
    generic_read = 0x80000000
    open_existing = 3
    file_flag_backup_semantics = 0x02000000  # lets this also probe a directory entry
    long_path = _to_long_path(path)
    handle = kernel32.CreateFileW(
        long_path, generic_read, 0, None, open_existing, file_flag_backup_semantics, None
    )
    invalid = wt.HANDLE(-1).value
    if handle == invalid or handle is None:
        error = ctypes.get_last_error()
        return error not in (2, 3)  # ERROR_FILE_NOT_FOUND / ERROR_PATH_NOT_FOUND: already gone
    kernel32.CloseHandle(handle)
    return False


def _to_long_path(path: str) -> str:
    if path.startswith("\\\\?\\"):
        return path
    absolute = os.path.abspath(path)  # noqa: PTH100 -- str path for the Win32 prefix
    if absolute.startswith("\\\\"):
        return "\\\\?\\UNC\\" + absolute[2:]
    return "\\\\?\\" + absolute


def _run_command(argv: Sequence[str], timeout: float, env: dict[str, str]) -> CommandResult:
    refuse_real_side_effect_under_pytest(f"run the real native tool {list(argv)!r}")
    try:
        proc = subprocess.run(  # noqa: S603 -- fixed allow-listed argv, shell=False
            list(argv),
            capture_output=True,
            text=True,
            timeout=timeout,
            env=env,
            check=False,
            stdin=subprocess.DEVNULL,
        )
    except subprocess.TimeoutExpired:
        return CommandResult(-1, "", "timed out", timed_out=True)
    except OSError as exc:
        return CommandResult(-1, "", f"{type(exc).__name__}: {exc}")
    return CommandResult(proc.returncode, proc.stdout, proc.stderr)


@dataclass(slots=True)
class RegenerableEnv:
    """Everything the tier reads from the machine, in one place so tests substitute it."""

    home: Path
    local_appdata: Path
    temp_roots: tuple[Path, ...]
    crash_dump_roots: tuple[Path, ...]
    now: Callable[[], float] = time.time
    running_process_names: Callable[[], frozenset[str]] = _real_running_process_names
    which: Callable[[str], str | None] = shutil.which
    run_command: Callable[[Sequence[str], float, dict[str, str]], CommandResult] = _run_command
    has_open_handle: Callable[[str], bool] = file_has_open_handle
    min_age_seconds: float = DEFAULT_MIN_AGE_SECONDS
    command_timeout_seconds: float = 300.0
    # Bounded wait for a tool that has its own cache lock (uv). Overridable so tests and the
    # scheduled task can pick a different bound.
    uv_lock_wait_seconds: float = UV_LOCK_WAIT_SECONDS
    disk_anchor: Path | None = None
    # ADR-0039: user exclusion patterns (`config.exclusion_patterns` -- `[safety] deny` globs and
    # one `*<name>*` glob per `[exclusions] project_names`). Any top-level entry whose full path,
    # or ANY path beneath it, matches is skipped whole and reported, never deleted. Native tool
    # cache roots and browser cache dirs are fixed, but are checked too (a match there is a
    # skipped_excluded item). Empty = no exclusions (the product default).
    excluded_patterns: tuple[str, ...] = ()
    # ADR-0034 addendum "pytest temp": the `pytest-of-<user>` directories to look in, the opt-in
    # mode (default off) and the age floor (its own constant, independent of `min_age_seconds`).
    pytest_temp_roots: tuple[Path, ...] = ()
    pytest_temp_mode: PytestTempMode = "off"
    pytest_temp_min_age_seconds: float = PYTEST_TEMP_MIN_AGE_SECONDS

    @classmethod
    def from_os_environment(cls) -> RegenerableEnv:
        home = Path(os.environ.get("USERPROFILE") or Path.home())
        local = Path(os.environ.get("LOCALAPPDATA") or home / "AppData" / "Local")
        temp = Path(os.environ.get("TEMP") or local / "Temp")
        windir = Path(os.environ.get("SYSTEMROOT") or "C:/Windows")
        program_data = Path(os.environ.get("PROGRAMDATA") or "C:/ProgramData")
        return cls(
            home=home,
            local_appdata=local,
            temp_roots=(temp, windir / "Temp"),
            crash_dump_roots=(
                local / "CrashDumps",
                local / "Microsoft" / "Windows" / "WER" / "ReportArchive",
                local / "Microsoft" / "Windows" / "WER" / "ReportQueue",
                program_data / "Microsoft" / "Windows" / "WER" / "ReportArchive",
                program_data / "Microsoft" / "Windows" / "WER" / "ReportQueue",
            ),
            disk_anchor=Path(os.environ.get("SYSTEMDRIVE", "C:") + "\\"),
            pytest_temp_roots=(temp / f"{_PYTEST_ROOT_PREFIX}{_pytest_user_name()}",),
        )


def _pytest_user_name() -> str:
    """The `<user>` pytest puts in `pytest-of-<user>` (`getpass.getuser()`, else "unknown")."""
    try:
        return getpass.getuser() or "unknown"
    except Exception:  # getpass raises OSError/KeyError/ImportError depending on platform
        return "unknown"


# --- Result types -----------------------------------------------------------------------------


@dataclass(slots=True)
class RegenerableItemResult:
    kind: ItemKind
    key: str
    label: str
    status: ItemStatus
    bytes_removed: int = 0
    files_removed: int = 0
    files_skipped_in_use: int = 0
    detail: str = ""
    skipped_paths: list[str] = field(default_factory=list)
    # ADR-0039: `"<path> :: <pattern>"` for every entry left alone because of a user exclusion.
    excluded: list[str] = field(default_factory=list)
    # Every top-level path this item actually handed to a delete (apply only) -- the set the
    # run report intersects with the exclusions to state `excluded_applied: 0` mechanically.
    applied_paths: list[str] = field(default_factory=list)


@dataclass(slots=True)
class RegenerableReport:
    run_id: str
    apply: bool
    started_at: float
    finished_at: float
    items: list[RegenerableItemResult]
    # Logical bytes the tier removed (sum of file sizes it unlinked / cache-dir shrinkage). For
    # hardlinked trees (uv's cache) this can exceed what the volume actually gained -- see
    # `disk_free_delta_bytes`, measured independently and including any other activity.
    bytes_removed: int
    disk_free_before_bytes: int | None
    disk_free_after_bytes: int | None

    @property
    def disk_free_delta_bytes(self) -> int | None:
        if self.disk_free_before_bytes is None or self.disk_free_after_bytes is None:
            return None
        return self.disk_free_after_bytes - self.disk_free_before_bytes

    @property
    def files_skipped_in_use(self) -> int:
        return sum(i.files_skipped_in_use for i in self.items)

    @property
    def excluded(self) -> list[str]:
        return [entry for i in self.items for entry in i.excluded]

    @property
    def applied_paths(self) -> list[str]:
        return [path for i in self.items for path in i.applied_paths]

    @property
    def duration_seconds(self) -> float:
        return self.finished_at - self.started_at


# --- Low-level filesystem helpers ---------------------------------------------------------------


def _is_reparse(st: os.stat_result) -> bool:
    return bool(getattr(st, "st_file_attributes", 0) & _FILE_ATTRIBUTE_REPARSE_POINT)


def dir_size_bytes(root: Path) -> int:
    """Logical size of every regular file under `root`, never following reparse points. Uses the
    scandir DirEntry stat (served from the directory listing on Windows -- no per-file syscall)."""
    total = 0
    stack = [str(root)]
    while stack:
        current = stack.pop()
        try:
            with os.scandir(current) as it:
                for entry in it:
                    try:
                        if entry.is_symlink():
                            continue
                        st = entry.stat(follow_symlinks=False)
                        if _is_reparse(st):
                            continue
                        if entry.is_dir(follow_symlinks=False):
                            stack.append(entry.path)
                        else:
                            total += st.st_size
                    except OSError:
                        continue
        except OSError:
            continue
    return total


@dataclass(slots=True)
class _TreeInfo:
    size: int = 0
    newest_mtime: float = 0.0
    guarded: bool = False
    files: int = 0


def _scan_tree(root: str) -> _TreeInfo:
    """Recursive size/newest-mtime/guard walk of one top-level entry (BS1 dogfood rule from
    #110: an entry's age is its NEWEST content, never the directory's own mtime)."""
    info = _TreeInfo()
    try:
        st = Path(root).lstat()
    except OSError:
        return info
    info.newest_mtime = st.st_mtime
    if not stat.S_ISDIR(st.st_mode) or _is_reparse(st):
        info.size = st.st_size if not stat.S_ISDIR(st.st_mode) else 0
        info.files = 0 if stat.S_ISDIR(st.st_mode) else 1
        return info
    stack = [root]
    while stack:
        current = stack.pop()
        try:
            with os.scandir(current) as it:
                for entry in it:
                    if entry.name.lower() in _GUARD_NAMES:
                        info.guarded = True
                    try:
                        est = entry.stat(follow_symlinks=False)
                    except OSError:
                        continue
                    info.newest_mtime = max(info.newest_mtime, est.st_mtime)
                    if _is_reparse(est):
                        continue
                    if entry.is_dir(follow_symlinks=False):
                        stack.append(entry.path)
                    else:
                        info.size += est.st_size
                        info.files += 1
        except OSError:
            continue
    return info


def _resolve_contained(path: Path, root: Path) -> bool:
    """True only if `path` resolves (symlinks/junctions followed) to somewhere inside `root`
    resolved the same way -- the escape check run before every top-level delete."""
    try:
        resolved = Path(os.path.realpath(path))
        resolved_root = Path(os.path.realpath(root))
    except OSError:
        return False
    return resolved != resolved_root and resolved_root in resolved.parents


def _delete_tree_contents(
    top: str,
    *,
    env: RegenerableEnv,
    result: RegenerableItemResult,
    remove_top: bool,
    enforce_age: bool = False,
) -> None:
    """Deletes files under `top` one at a time. Never descends into a reparse point (the entry
    itself is removed, its target untouched). A file with an open handle, or one that fails to
    delete, is skipped and counted -- never forced. Empty directories are removed bottom-up.

    `enforce_age` (ADR-0036): the caller's selection rule was "newest content older than
    `env.min_age_seconds`" (aged TEMP / crash dumps), so each file is re-checked against that
    rule right before its unlink -- a file touched since the plan is skipped, not deleted."""
    assert_not_real_profile_under_pytest(top, operation="delete the contents of")
    dirs_to_try: list[str] = []
    stack = [top]
    while stack:
        current = stack.pop()
        dirs_to_try.append(current)
        try:
            with os.scandir(current) as it:
                entries = list(it)
        except OSError:
            continue
        for entry in entries:
            try:
                est = entry.stat(follow_symlinks=False)
            except OSError:
                continue
            if _is_reparse(est):
                _remove_reparse_entry(entry.path, est, result, env=env, enforce_age=enforce_age)
                continue
            if entry.is_dir(follow_symlinks=False):
                stack.append(entry.path)
                continue
            _delete_one_file(entry.path, est, env=env, result=result, enforce_age=enforce_age)
    for directory in reversed(dirs_to_try):
        if directory == top and not remove_top:
            continue
        # Non-empty (something was skipped) or in use: leave it, never force.
        with contextlib.suppress(OSError):
            os.rmdir(directory)  # noqa: PTH106 -- str path, may be long


def _changed_since_plan(
    path: str, planned: os.stat_result, *, env: RegenerableEnv, enforce_age: bool
) -> bool | None:
    """ADR-0036: re-stat `path` immediately before an unlink. True means "do not delete":
    its mtime or size differs from `planned` (the stat the walk took), or, when `enforce_age`,
    its live mtime is younger than `env.min_age_seconds` relative to `env.now()` (the age floor
    the plan was selected under). None means the path is already gone (nothing to delete or
    skip). Fail-closed: a stat error other than "gone" counts as changed."""
    try:
        live = Path(path).lstat()
    except FileNotFoundError:
        return None
    except OSError:
        return True
    if live.st_mtime != planned.st_mtime or live.st_size != planned.st_size:
        return True
    if _is_reparse(live) != _is_reparse(planned) or stat.S_ISDIR(live.st_mode) != stat.S_ISDIR(
        planned.st_mode
    ):
        return True
    return enforce_age and (env.now() - live.st_mtime) < env.min_age_seconds


def _remove_reparse_entry(
    path: str,
    st: os.stat_result,
    result: RegenerableItemResult,
    *,
    env: RegenerableEnv,
    enforce_age: bool = False,
) -> None:
    """A junction/symlink inside an allow-listed tree: remove the link itself only."""
    assert_not_real_profile_under_pytest(path, operation="remove the link", link_itself=True)
    changed = _changed_since_plan(path, st, env=env, enforce_age=enforce_age)
    if changed is None:
        return
    if changed:
        _record_skip(result, path)
        return
    try:
        if stat.S_ISDIR(st.st_mode):
            os.rmdir(path)  # noqa: PTH106
        else:
            os.unlink(path)  # noqa: PTH108
    except OSError:
        _record_skip(result, path)


def _delete_one_file(
    path: str,
    planned: os.stat_result,
    *,
    env: RegenerableEnv,
    result: RegenerableItemResult,
    enforce_age: bool = False,
) -> None:
    assert_not_real_profile_under_pytest(path, operation="delete the file")
    size = planned.st_size
    if env.has_open_handle(path):
        _record_skip(result, path)
        return
    # ADR-0036: re-stat AFTER the (slow) handle probe and immediately before the unlink -- a file
    # appended to or touched since the plan is in active use, even when no handle is open now.
    changed = _changed_since_plan(path, planned, env=env, enforce_age=enforce_age)
    if changed is None:
        return
    if changed:
        _record_skip(result, path)
        return
    try:
        try:
            os.unlink(path)  # noqa: PTH108
        except PermissionError:
            os.chmod(path, stat.S_IWRITE)  # noqa: PTH101 -- clear read-only, retry once
            os.unlink(path)  # noqa: PTH108
    except FileNotFoundError:
        return
    except OSError:
        _record_skip(result, path)
        return
    result.bytes_removed += size
    result.files_removed += 1


_MAX_SKIPPED_PATHS_RECORDED = 25


def _record_skip(result: RegenerableItemResult, path: str) -> None:
    result.files_skipped_in_use += 1
    if len(result.skipped_paths) < _MAX_SKIPPED_PATHS_RECORDED:
        result.skipped_paths.append(path)


# --- Per-kind runners ---------------------------------------------------------------------------


def _tool_cache_root(env: RegenerableEnv, spec: NativeToolSpec) -> Path:
    base = env.local_appdata if spec.cache_root_relative_to == "local_appdata" else env.home
    return base / Path(spec.cache_root_tail)


def _run_native_tool(
    spec: NativeToolSpec, env: RegenerableEnv, *, apply: bool
) -> RegenerableItemResult:
    result = RegenerableItemResult("native_command", spec.key, spec.label, "nothing_to_clean")
    exe = env.which(spec.executable)
    if exe is None:
        result.status = "skipped_tool_missing"
        result.detail = f"`{spec.executable}` is not on PATH"
        return result
    cache_root = _tool_cache_root(env, spec)
    if not cache_root.is_dir():
        result.status = "skipped_not_present"
        result.detail = f"{cache_root} does not exist"
        return result
    if not spec.own_lock:
        # pip/yarn/conda (and npm, which has no busy names) have no lock this module can rely on
        # (BELIEVED, not measured here), so a running process is the only in-use signal: skip.
        try:
            running = env.running_process_names()
        except OSError:
            result.status = "skipped_in_use"
            result.detail = "could not enumerate running processes; skipped (fail-closed)"
            return result
        busy = sorted(spec.busy_process_names & running)
        if busy:
            result.status = "skipped_in_use"
            result.detail = f"{', '.join(busy)} is running; the tool may hold its cache lock"
            return result

    root_hit = first_matching_pattern(cache_root, env.excluded_patterns, is_dir=True)
    if root_hit is not None:
        result.status = "skipped_excluded"
        result.excluded.append(f"{cache_root} :: {root_hit}")
        result.detail = f"{cache_root} matches the user exclusion {root_hit!r}; left alone"
        return result

    before = dir_size_bytes(cache_root)
    if not apply:
        result.status = "would_clean" if before > 0 else "nothing_to_clean"
        result.bytes_removed = before
        result.detail = f"`{spec.executable} {' '.join(spec.argv_tail)}` (dry run)"
        return result

    child_env = dict(os.environ)
    timeout = env.command_timeout_seconds
    wait = env.uv_lock_wait_seconds
    if spec.own_lock:
        # Wait for the tool's own lock (never `--force` past it); the expiry is the only skip.
        child_env["UV_LOCK_TIMEOUT"] = str(int(wait))
        timeout = wait + _LOCK_WAIT_KILL_MARGIN_SECONDS
    argv = [exe, *spec.argv_tail]
    result.applied_paths.append(str(cache_root))
    outcome = env.run_command(argv, timeout, child_env)
    after = dir_size_bytes(cache_root)
    result.bytes_removed = max(0, before - after)
    combined = f"{outcome.stdout}\n{outcome.stderr}".lower()
    lock_expired = outcome.timed_out or ("timeout" in combined and "lock" in combined)
    if spec.own_lock and lock_expired:
        result.status = "skipped_in_use"
        result.detail = f"waited {int(wait)} s for {spec.key}'s cache lock"
    elif lock_expired:
        result.status = "skipped_in_use"
        result.detail = "tool is in use by another process (lock timeout); skipped"
    elif outcome.returncode != 0 and _file_in_use_error(combined):
        # Measured 2026-10-01 (pip 25.1): `pip cache purge` takes NO global lock; with one cache
        # file held open it removes every other file and then exits 2 with a PermissionError
        # traceback. There is nothing to wait on, so this is a partial purge reported as a skip.
        result.status = "skipped_in_use"
        result.detail = "a cache file is open in another process; the rest was removed"
    elif outcome.returncode != 0:
        result.status = "failed"
        result.detail = (outcome.stderr or outcome.stdout).strip()[
            :300
        ] or f"exit {outcome.returncode}"
    else:
        result.status = "cleaned" if result.bytes_removed > 0 else "nothing_to_clean"
        result.detail = f"`{spec.executable} {' '.join(spec.argv_tail)}` exit 0"
    return result


def _file_in_use_error(lowered_output: str) -> bool:
    """True if a tool's lower-cased output says a file was held open by another process."""
    return any(
        marker in lowered_output
        for marker in ("permissionerror", "being used by another process", "winerror 32")
    )


def _aged_children(
    root: Path, env: RegenerableEnv, kind: ItemKind, key: str, label: str, *, apply: bool
) -> RegenerableItemResult:
    """Cleans the direct children of `root` whose NEWEST content is older than the age floor."""
    result = RegenerableItemResult(kind, key, label, "nothing_to_clean")
    if not root.is_dir():
        result.status = "skipped_not_present"
        result.detail = f"{root} does not exist"
        return result
    root_hit = first_matching_pattern(root, env.excluded_patterns, is_dir=True)
    if root_hit is not None:
        result.status = "skipped_excluded"
        result.excluded.append(f"{root} :: {root_hit}")
        result.detail = f"{root} matches the user exclusion {root_hit!r}; left alone"
        return result
    now = env.now()
    try:
        children = [entry.path for entry in os.scandir(root)]
    except PermissionError:
        # Running unelevated is the invariant (reclaim.elevation.assert_not_elevated): an
        # admin-only root such as C:\Windows\Temp is out of reach, not a failure.
        result.status = "skipped_no_access"
        result.detail = f"{root} needs administrator rights; skipped"
        return result
    except OSError as exc:
        result.status = "failed"
        result.detail = f"cannot list {root}: {type(exc).__name__}"
        return result
    guarded: list[str] = []
    pytest_roots_left = 0
    for child in children:
        child_path = Path(child)
        if kind == "aged_temp" and child_path.name.lower().startswith(_PYTEST_ROOT_PREFIX):
            # ADR-0034 addendum "pytest temp": `pytest-of-<user>` is shared by every project the
            # user tests, so it is never swept wholesale as "old temp" -- only the opt-in
            # `pytest_temp` category, one `pytest-<N>` at a time, may touch it.
            pytest_roots_left += 1
            continue
        if not _resolve_contained(child_path, root) and not _is_reparse_or_missing(child):
            continue
        # ADR-0039: BEFORE the age/guard logic and before anything is measured for deletion. The
        # whole top-level entry is skipped when the entry OR anything beneath it matches: a
        # deletable-looking parent (`%TEMP%/claude`) must not take an excluded child with it.
        # A reparse point is removed as a link entry (its target is never walked or touched), so
        # only the link's own path is checked.
        exclusion_hit = (
            first_matching_pattern(child, env.excluded_patterns, is_dir=True)
            if _is_reparse_or_missing(child)
            else subtree_exclusion_match(child, env.excluded_patterns)
        )
        if exclusion_hit is not None:
            result.excluded.append(f"{child} :: {exclusion_hit}")
            continue
        info = _scan_tree(child)
        age = now - info.newest_mtime
        if age < env.min_age_seconds or info.newest_mtime <= 0:
            continue
        if info.guarded:
            guarded.append(child_path.name)
            continue
        if not apply:
            result.bytes_removed += info.size
            result.files_removed += info.files
            continue
        try:
            st = Path(child).lstat()
        except OSError:
            continue
        result.applied_paths.append(child)
        if _is_reparse(st):
            _remove_reparse_entry(child, st, result, env=env, enforce_age=True)
        elif stat.S_ISDIR(st.st_mode):
            _delete_tree_contents(child, env=env, result=result, remove_top=True, enforce_age=True)
        else:
            _delete_one_file(child, st, env=env, result=result, enforce_age=True)
    if guarded:
        result.detail = (
            f"left {len(guarded)} entr{'y' if len(guarded) == 1 else 'ies'} that contain a "
            f"git repo / virtualenv / node_modules for review: {', '.join(guarded[:5])}"
        )
    if result.excluded:
        count = len(result.excluded)
        note = f"left {count} excluded entr{'y' if count == 1 else 'ies'} alone"
        result.detail = f"{result.detail}; {note}" if result.detail else note
    if pytest_roots_left:
        note = "left pytest-of-<user> alone (the opt-in pytest temp category owns it)"
        result.detail = f"{result.detail}; {note}" if result.detail else note
    if apply:
        result.status = "cleaned" if result.files_removed else "nothing_to_clean"
    else:
        result.status = "would_clean" if result.bytes_removed else "nothing_to_clean"
    return result


_MAX_LISTED_PYTEST_DIRS = 25


def _any_open_handle(top: str, env: RegenerableEnv) -> str | None:
    """None if no file under `top` has an open handle; otherwise a human reason. Fail-closed: a
    detector that raises is reported as a reason, never as 'no handle'. Reparse points are not
    followed (only their own entry is skipped)."""
    stack = [top]
    while stack:
        current = stack.pop()
        try:
            with os.scandir(current) as it:
                entries = list(it)
        except OSError as exc:
            return f"cannot list {current}: {type(exc).__name__}"
        for entry in entries:
            try:
                est = entry.stat(follow_symlinks=False)
                if _is_reparse(est):
                    continue
                if entry.is_dir(follow_symlinks=False):
                    stack.append(entry.path)
                    continue
            except OSError as exc:
                return f"cannot stat {entry.path}: {type(exc).__name__}"
            try:
                if env.has_open_handle(entry.path):
                    return f"{entry.path} is open in another process"
            except Exception as exc:  # any detector failure must fail closed
                return f"open-handle check failed on {entry.path}: {type(exc).__name__}"
    return None


def _run_pytest_temp(
    root: Path, key: str, label: str, env: RegenerableEnv, *, apply: bool
) -> RegenerableItemResult:
    """ADR-0034 addendum "pytest temp": deletes whole `pytest-<N>` basetemp directories directly
    inside `root` (a `pytest-of-<user>` dir) whose NEWEST content is at least
    `env.pytest_temp_min_age_seconds` old. All-or-nothing per directory: a directory with any
    open file, any recent file, or any exclusion match beneath it is left entirely alone. The
    product cannot tell which project created a given directory (ownership unknown), which is why
    `env.pytest_temp_mode` must be "delete" for `apply` to do anything. A dry run never probes
    open handles (that opens each file)."""
    result = RegenerableItemResult("pytest_temp", key, label, "nothing_to_clean")
    apply = apply and env.pytest_temp_mode == "delete"
    try:
        root_st = root.lstat()
    except OSError:
        result.status = "skipped_not_present"
        result.detail = f"{root} does not exist"
        return result
    if not stat.S_ISDIR(root_st.st_mode) or _is_reparse(root_st):
        result.status = "skipped_not_present"
        result.detail = f"{root} is not a plain directory; not followed"
        return result
    root_hit = first_matching_pattern(root, env.excluded_patterns, is_dir=True)
    if root_hit is not None:
        result.status = "skipped_excluded"
        result.excluded.append(f"{root} :: {root_hit}")
        result.detail = f"{root} matches the user exclusion {root_hit!r}; left alone"
        return result
    try:
        entries = list(os.scandir(root))
    except PermissionError:
        result.status = "skipped_no_access"
        result.detail = f"{root} is not readable; skipped"
        return result
    except OSError as exc:
        result.status = "failed"
        result.detail = f"cannot list {root}: {type(exc).__name__}"
        return result

    penv = dataclasses.replace(env, min_age_seconds=env.pytest_temp_min_age_seconds)
    now = env.now()
    listing: list[str] = []
    found = qualifying = in_use = dirs_removed = 0
    guarded: list[str] = []
    left_reasons: list[str] = []  # apply only: why a qualifying dir was not fully removed
    for entry in sorted(entries, key=lambda e: e.name):
        if _PYTEST_BASETEMP_RE.fullmatch(entry.name) is None:
            continue  # includes the `pytest-current` link and every unrelated sibling
        child = entry.path
        try:
            est = entry.stat(follow_symlinks=False)
        except OSError:
            continue
        if _is_reparse(est) or not stat.S_ISDIR(est.st_mode):
            continue  # a link or a file named like a basetemp: never followed, never deleted
        found += 1
        hit = subtree_exclusion_match(child, env.excluded_patterns)
        if hit is not None:
            result.excluded.append(f"{child} :: {hit}")
            continue
        info = _scan_tree(child)
        age = now - info.newest_mtime
        qualifies = age >= env.pytest_temp_min_age_seconds and info.newest_mtime > 0
        if len(listing) < _MAX_LISTED_PYTEST_DIRS:
            if info.newest_mtime <= 0:
                verdict = "unknown age (mtime 0), left alone"
            else:
                verdict = "older than the floor" if qualifies else "too recent"
            listing.append(f"{entry.name} ({age / 86400:.1f} d, {info.size} B, {verdict})")
        if not qualifies:
            continue
        if info.guarded:
            guarded.append(entry.name)
            continue
        qualifying += 1
        if not apply:
            result.bytes_removed += info.size
            result.files_removed += info.files
            continue
        reason = _any_open_handle(child, penv)
        if reason is not None:
            in_use += 1
            _record_skip(result, child)
            left_reasons.append(f"{entry.name} left whole: {reason[:200]}")
            continue
        # ADR-0036: re-scan AFTER the (slow) handle probe, immediately before the delete -- a
        # directory touched since the plan (any file newer) is in use, even with no handle now.
        live = _scan_tree(child)
        if live.newest_mtime != info.newest_mtime or (
            env.now() - live.newest_mtime < env.pytest_temp_min_age_seconds
        ):
            in_use += 1
            _record_skip(result, child)
            left_reasons.append(f"{entry.name} left whole: touched since it was planned")
            continue
        result.applied_paths.append(child)
        skipped_before = result.files_skipped_in_use
        _delete_tree_contents(child, env=penv, result=result, remove_top=True, enforce_age=True)
        if not Path(child).exists():
            dirs_removed += 1
        else:
            # All-or-nothing was only guaranteed for a handle present at probe time: anything
            # that appeared after it (a new handle, a touched file, a process whose cwd is in the
            # folder) leaves a partial dir, which must never be reported as cleaned.
            in_use += 1
            held = result.files_skipped_in_use - skipped_before
            why = (
                f"{held} file(s) in use or touched" if held else "folder still in use by a process"
            )
            left_reasons.append(f"{entry.name} only partly removed, remainder left: {why}")

    notes = [
        f"{found} pytest-<N> folder(s), {qualifying} at least "
        f"{env.pytest_temp_min_age_seconds / 86400:g} d old; ownership of each is unknown to "
        "Reclaim (shared by every project run by this user)"
    ]
    if listing:
        notes.append("; ".join(listing))
    if guarded:
        notes.append(f"left {len(guarded)} with a git repo / virtualenv inside: {guarded[:5]}")
    if result.excluded:
        notes.append(f"left {len(result.excluded)} excluded folder(s) alone")
    notes.extend(left_reasons)
    result.detail = " | ".join(notes)
    cleaned = bool(result.files_removed or dirs_removed) if apply else qualifying > 0
    if in_use:
        # Even if other dirs were removed: never say "cleaned" while any qualifying dir remains.
        result.status = "skipped_in_use"
    elif cleaned:
        result.status = "cleaned" if apply else "would_clean"
    elif result.excluded:
        result.status = "skipped_excluded"
    return result


def _is_reparse_or_missing(path: str) -> bool:
    """A top-level reparse point is removed as the link entry itself (its target is never
    touched), so the containment check is not applicable to it."""
    try:
        return _is_reparse(Path(path).lstat())
    except OSError:
        return True


def _browser_profile_dirs(local: Path, spec: BrowserSpec) -> list[Path]:
    profiles: list[Path] = []
    for rel in spec.profile_roots:
        root = local / Path(rel)
        if not root.is_dir():
            continue
        try:
            children = [Path(e.path) for e in os.scandir(root) if e.is_dir(follow_symlinks=False)]
        except OSError:
            continue
        if spec.key == "firefox":
            profiles.extend(children)
        else:
            profiles.extend(c for c in children if c.name.startswith(_CHROMIUM_PROFILE_PREFIXES))
    return profiles


def _run_browser(spec: BrowserSpec, env: RegenerableEnv, *, apply: bool) -> RegenerableItemResult:
    result = RegenerableItemResult(
        "browser_cache", spec.key, f"{spec.label} cache", "nothing_to_clean"
    )
    profiles = _browser_profile_dirs(env.local_appdata, spec)
    targets = [p / name for p in profiles for name in spec.cache_dir_names if (p / name).is_dir()]
    kept: list[Path] = []
    for target in targets:
        hit = first_matching_pattern(target, env.excluded_patterns, is_dir=True)
        if hit is None:
            kept.append(target)
        else:
            result.excluded.append(f"{target} :: {hit}")
    if targets and not kept:
        result.status = "skipped_excluded"
        result.detail = f"every {spec.label} cache directory matches a user exclusion"
        return result
    targets = kept
    if not targets:
        result.status = "skipped_not_present"
        result.detail = f"no {spec.label} cache directories found"
        return result
    try:
        running = env.running_process_names()
    except OSError:
        result.status = "skipped_browser_running"
        result.detail = "could not enumerate running processes; skipped (fail-closed)"
        return result
    if spec.process_names & running:
        result.status = "skipped_browser_running"
        result.detail = f"{spec.label} is running; its cache is left alone"
        return result
    for target in targets:
        if not apply:
            result.bytes_removed += dir_size_bytes(target)
            continue
        result.applied_paths.append(str(target))
        _delete_tree_contents(str(target), env=env, result=result, remove_top=False)
    if apply:
        result.status = "cleaned" if result.files_removed else "nothing_to_clean"
    else:
        result.status = "would_clean" if result.bytes_removed else "nothing_to_clean"
    return result


# --- Public API ---------------------------------------------------------------------------------


def _measure_free(anchor: Path | None) -> int | None:
    if anchor is None:
        return None
    try:
        return shutil.disk_usage(anchor).free
    except OSError:
        return None


@dataclass(frozen=True, slots=True)
class _PlannedItem:
    key: str
    kind: ItemKind
    label: str
    runner: Callable[[], RegenerableItemResult]
    # True for an item that may block for a long, bounded time on a tool's own lock: it runs
    # last so every other item is finished and reported before the wait starts.
    waits_on_lock: bool = False


def _plan_items(
    resolved: RegenerableEnv, *, apply: bool, only_keys: frozenset[str] | None = None
) -> list[_PlannedItem]:
    planned = _plan_all_items(resolved, apply=apply)
    if only_keys is None:
        return planned
    # Narrowing only: a key can never add an item the allow-list does not already plan.
    return [item for item in planned if item.key in only_keys]


def _plan_all_items(resolved: RegenerableEnv, *, apply: bool) -> list[_PlannedItem]:
    planned: list[_PlannedItem] = [
        _PlannedItem(
            spec.key,
            "native_command",
            spec.label,
            functools.partial(_run_native_tool, spec, resolved, apply=apply),
            waits_on_lock=spec.own_lock,
        )
        for spec in NATIVE_TOOLS
    ]
    for index, root in enumerate(resolved.temp_roots):
        label = f"Old temp files ({root})"
        planned.append(
            _PlannedItem(
                f"temp{index}",
                "aged_temp",
                label,
                functools.partial(
                    _aged_children,
                    root,
                    resolved,
                    "aged_temp",
                    f"temp{index}",
                    label,
                    apply=apply,
                ),
            )
        )
    for index, root in enumerate(resolved.crash_dump_roots):
        label = f"Old crash dumps ({root})"
        planned.append(
            _PlannedItem(
                f"crash{index}",
                "crash_dump",
                label,
                functools.partial(
                    _aged_children,
                    root,
                    resolved,
                    "crash_dump",
                    f"crash{index}",
                    label,
                    apply=apply,
                ),
            )
        )
    if resolved.pytest_temp_mode != "off":
        for index, root in enumerate(resolved.pytest_temp_roots):
            label = f"Old pytest temp folders ({root})"
            planned.append(
                _PlannedItem(
                    f"pytest{index}",
                    "pytest_temp",
                    label,
                    functools.partial(
                        _run_pytest_temp, root, f"pytest{index}", label, resolved, apply=apply
                    ),
                )
            )
    planned.extend(
        _PlannedItem(
            browser.key,
            "browser_cache",
            f"{browser.label} cache",
            functools.partial(_run_browser, browser, resolved, apply=apply),
        )
        for browser in BROWSERS
    )
    # Stable sort: lock-waiting items last, everything else keeps its allow-list order.
    return sorted(planned, key=lambda item: item.waits_on_lock)


def run_regenerable_clean(
    env: RegenerableEnv | None = None,
    *,
    apply: bool,
    audit_log_path: Path | None = DEFAULT_AUDIT_LOG_PATH,
    on_item_start: Callable[[str, str, bool], None] | None = None,
    on_item_done: Callable[[RegenerableItemResult], None] | None = None,
    run_id: str | None = None,
    only_keys: frozenset[str] | None = None,
) -> RegenerableReport:
    """Runs the whole allow-list. NEVER raises for a per-item problem: each item reports its own
    status. Every item (and every skipped/failed path, up to a cap) is appended to the audit
    log as one JSON line, written whether or not `apply` is set (dry runs are marked).

    Items that may wait on a tool's own lock (uv) run last. The optional callbacks let a caller
    show live progress: `on_item_start(key, label, waits_on_lock)` before each item and
    `on_item_done(result)` after it. They are observers only -- an exception raised by one is
    logged and swallowed so a UI bug can never abort a clean.

    `only_keys` (the scheduled logon retry) restricts the run to the allow-list items with those
    keys; it can only narrow the plan, never add to it."""
    resolved = env if env is not None else RegenerableEnv.from_os_environment()
    if apply:
        # Refuse before ANY item runs (the per-item guards below are the backstop).
        for root in (
            resolved.home,
            resolved.local_appdata,
            *resolved.temp_roots,
            *resolved.crash_dump_roots,
            *resolved.pytest_temp_roots,
        ):
            assert_not_real_profile_under_pytest(root, operation="apply a clean against")
    run_id = run_id or uuid.uuid4().hex[:12]
    started = resolved.now()
    free_before = _measure_free(resolved.disk_anchor)

    items: list[RegenerableItemResult] = []
    for planned in _plan_items(resolved, apply=apply, only_keys=only_keys):
        if on_item_start is not None:
            _notify(on_item_start, planned.key, planned.label, planned.waits_on_lock)
        item = _guarded(planned.runner, planned.key, planned.kind, planned.label)
        items.append(item)
        if on_item_done is not None:
            _notify(on_item_done, item)

    finished = resolved.now()
    free_after = _measure_free(resolved.disk_anchor) if apply else None
    report = RegenerableReport(
        run_id=run_id,
        apply=apply,
        started_at=started,
        finished_at=finished,
        items=items,
        bytes_removed=sum(i.bytes_removed for i in items),
        disk_free_before_bytes=free_before if apply else None,
        disk_free_after_bytes=free_after,
    )
    _write_audit(report, audit_log_path)
    logger.info(
        "regenerable.run_finished",
        run_id=run_id,
        apply=apply,
        bytes_removed=report.bytes_removed,
        skipped_in_use=report.files_skipped_in_use,
        duration_s=round(report.duration_seconds, 2),
    )
    return report


def count_excluded_applied(applied_paths: Sequence[str], patterns: Sequence[str]) -> int:
    """How many of the paths a run actually handed to a delete match a user exclusion -- the
    mechanical form of "none of the excluded projects appeared among applied candidates". Must be
    0; a non-zero value is a bug in this module's own skip logic, so callers treat it as a hard
    failure (ADR-0039)."""
    return sum(
        1
        for path in applied_paths
        if first_matching_pattern(path, patterns, is_dir=True) is not None
    )


def _notify(callback: Callable[..., None], *args: object) -> None:
    try:
        callback(*args)
    except Exception:
        logger.warning("regenerable.progress_callback_failed", exc_info=True)


def _guarded(
    runner: Callable[[], RegenerableItemResult], key: str, kind: ItemKind, label: str
) -> RegenerableItemResult:
    try:
        return runner()
    except Exception as exc:
        logger.warning("regenerable.item_failed", key=key, exc_info=True)
        return RegenerableItemResult(
            kind, key, label, "failed", detail=f"{type(exc).__name__}: {exc}"[:300]
        )


def _write_audit(report: RegenerableReport, path: Path | None) -> None:
    if path is None:
        return
    try:
        path.parent.mkdir(parents=True, exist_ok=True)
        with path.open("a", encoding="utf-8") as fh:
            for item in report.items:
                fh.write(
                    json.dumps(
                        {
                            "ts": report.started_at,
                            "run_id": report.run_id,
                            "apply": report.apply,
                            "kind": item.kind,
                            "key": item.key,
                            "label": item.label,
                            "status": item.status,
                            "bytes_removed": item.bytes_removed,
                            "files_removed": item.files_removed,
                            "files_skipped_in_use": item.files_skipped_in_use,
                            "skipped_paths": item.skipped_paths,
                            "excluded": item.excluded,
                            "detail": item.detail,
                        }
                    )
                    + "\n"
                )
            fh.write(
                json.dumps(
                    {
                        "ts": report.finished_at,
                        "run_id": report.run_id,
                        "summary": True,
                        "apply": report.apply,
                        "bytes_removed": report.bytes_removed,
                        "disk_free_delta_bytes": report.disk_free_delta_bytes,
                        "duration_seconds": round(report.duration_seconds, 3),
                    }
                )
                + "\n"
            )
    except OSError:
        # An unwritable audit log must not turn a successful clean into a crash -- but it is
        # never silent: the structured log carries the failure.
        logger.warning("regenerable.audit_write_failed", path=str(path), exc_info=True)
