; Reclaim installer script (Inno Setup 6/7).
;
; Per-user install, no admin required — matches reclaim.elevation.assert_not_elevated's
; refusal to ever run elevated (this tool must never need, request, or run under UAC
; elevation, at install time or run time). Installs the Nuitka --standalone build produced by
; packaging/build_installer.ps1 into the user's own AppData, and points every shortcut's
; working directory at the install folder itself so reclaim's relative data/ and config.toml
; paths land somewhere the user already owns.

#define MyAppName "Reclaim"
#define MyAppVersion "1.3.0"
#define MyAppPublisher "Gaurav Gandhi"
#define MyAppExeName "reclaim.exe"
#define MyDistDir "build\entry_point.dist"

[Setup]
AppId={{B6C1B6C7-6B6A-4E3B-9B7B-2B7E1E7C6A21}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
DefaultDirName={autopf}\{#MyAppName}
; Per-user default (no admin dialog, no UAC prompt) — matches the "never elevated" invariant.
PrivilegesRequired=lowest
DefaultGroupName={#MyAppName}
DisableProgramGroupPage=yes
OutputBaseFilename=reclaim-setup
OutputDir=dist
Compression=lzma2
SolidCompression=yes
WizardStyle=modern
LicenseFile=..\LICENSE
UninstallDisplayIcon={app}\{#MyAppExeName}
; Brand assets generated by packaging/build_brand_assets.py from the same geometry as
; src/reclaim/api/static/logo.svg — regenerate with `uv run python packaging/build_brand_assets.py`
; if the mark ever changes.
SetupIconFile=reclaim.ico
WizardSmallImageFile=wizard_small.bmp
WizardImageFile=wizard_large.bmp
ArchitecturesAllowed=x64compatible
ArchitecturesInstallIn64BitMode=x64compatible

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "Create a &desktop shortcut"; GroupDescription: "Additional shortcuts:"; Flags: unchecked

[Files]
Source: "{#MyDistDir}\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
; Third-party notices (NOTICES.md) — the dashboard's /NOTICES route reads this relative to the
; process's own working directory ({app}, per the [Icons] "Start in" note below), same pattern
; as the LICENSE-acceptance page's LicenseFile= above needing the repo-root LICENSE at build time.
Source: "..\NOTICES.md"; DestDir: "{app}"; Flags: ignoreversion
; P0-2 fix (2026-08 audit): without this, a fresh install had NO config.toml anywhere and every
; cleanup category shipped enabled=false -- "Clean My Computer" produced zero results, forever,
; with no discoverable fix. Installed as config.toml itself (reclaim.cli's default relative
; path -- see the [Icons] "Start in" note above) so a fresh install gets real default-ON
; categories out of the box. destfilename= renames it on the way in since Source's own basename
; deliberately isn't "config.toml" (that name is gitignored -- see .gitignore's "User's real
; config" entry -- so the repo-tracked source file needs a different name). onlyifdoesntexist:
; an upgrade over an existing install must never clobber a user's already-customized config.toml.
Source: "config.default.toml"; DestDir: "{app}"; DestName: "config.toml"; Flags: onlyifdoesntexist

[Icons]
; "Start in" is deliberately {app} (not {userdocs} or anything else) — reclaim's CLI defaults
; (data/, config.toml, data/mode_log.jsonl) are relative paths, so this is what makes them land
; in the per-user install folder the user already owns, rather than silently landing in
; whatever directory Explorer happened to launch the shortcut from.
Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Parameters: "dashboard"; WorkingDir: "{app}"
Name: "{group}\Uninstall {#MyAppName}"; Filename: "{uninstallexe}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Parameters: "dashboard"; WorkingDir: "{app}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Parameters: "dashboard"; WorkingDir: "{app}"; Description: "Launch {#MyAppName}"; Flags: postinstall nowait skipifsilent unchecked

[Code]
// fix/uninstaller-terminate-running-process: a Reclaim server process (the dashboard, or a
// background scan/apply/AI-analysis worker it spawned) holds an OS-level lock on reclaim.exe
// and its loaded DLLs for as long as it's running. Inno's own [Files] removal pass can't clear
// that lock, and used to fail SILENTLY on each locked file rather than aborting the uninstall
// -- Add/Remove Programs correctly reported the app gone (registry entry + shortcuts removed)
// while ~30 program files, still holding real locks, survived on disk. Observed for real: a
// scan-worker process outlived a killed parent and kept writing to data\logs\reclaim.log for
// a full minute after the uninstaller's file-removal pass had already run past it.
//
// InitializeUninstall is the very first thing Inno calls, before any removal begins -- killing
// the process tree here, not at usUninstall's start, means the removal pass itself never has to
// contend with a live process at all.
function InitializeUninstall(): Boolean;
var
  ResultCode: Integer;
begin
  Result := True;
  // /T also kills child processes of the tree (a scan/AI worker spawned via multiprocessing)
  // -- killing only the top-level dashboard process and leaving a worker running is exactly
  // the incident above. /F force-terminates; taskkill exits 0 (killed) or 128 (nothing was
  // running, not an error) -- neither is worth surfacing, and this never needs admin rights to
  // kill a process the current non-elevated user already owns (this installer is always
  // per-user/non-elevated -- see PrivilegesRequired=lowest above).
  Exec('taskkill.exe', '/F /T /IM {#MyAppExeName}', '', SW_HIDE, ewWaitUntilTerminated, ResultCode);
  // Windows releases a terminated process's file handles as part of process teardown, which is
  // prompt but not guaranteed synchronous with taskkill.exe's own exit -- and a freshly-freed
  // reclaim.exe is exactly the kind of file Defender's real-time scanner re-locks transiently
  // right after a process release it (see packaging/RELEASE_RUNBOOK.md's cold-start scan note).
  // A short wait here is cheap insurance against exactly that race.
  Sleep(500);
end;

// Directory enumeration helper for the leftover-file check in CurUninstallStepChanged below --
// True if {app} contains anything other than `data\` (which the [Files] section never lists,
// so Inno's own removal pass never touches it -- see the data-folder-preservation comment
// further down). A non-empty result here means InitializeUninstall's taskkill above didn't
// fully do its job.
function AppDirHasLeftoverFiles(AppDir: String): Boolean;
var
  FindRec: TFindRec;
begin
  Result := False;
  if FindFirst(AppDir + '\*', FindRec) then
  begin
    try
      repeat
        if (FindRec.Name <> '.') and (FindRec.Name <> '..') and (FindRec.Name <> 'data') then
          Result := True;
      until (not FindNext(FindRec)) or Result;
    finally
      FindClose(FindRec);
    end;
  end;
end;

// Reclaim's data (scan index, quarantine vault, mode/apply logs — see the [Icons] comment above
// for why these are relative paths under {app}\data) survives a normal uninstall by default: the
// [Files] section above only ever lists the Nuitka --standalone build output, never {app}\data,
// so Inno Setup's own file-removal pass never touches it. This handler adds the explicit,
// opt-in "also delete my data" step GG's uninstall spec calls for, asked only after the program
// files are already gone (usPostUninstall) so a Cancel/No leaves a fully-working, reinstallable
// data folder behind.
procedure CurUninstallStepChanged(CurUninstallStep: TUninstallStep);
var
  DataDir: String;
  AppDir: String;
  Response: Integer;
begin
  if CurUninstallStep = usPostUninstall then
  begin
    // Defensive verification, not the primary fix (InitializeUninstall's taskkill above is):
    // confirm the removal pass this step follows actually left {app} clean. One retry after a
    // short wait covers a transient re-lock (e.g. Defender); if it's STILL not clean after
    // that, say so plainly instead of leaving silent orphans with no signal at all -- the
    // original bug this whole change fixes.
    AppDir := ExpandConstant('{app}');
    if AppDirHasLeftoverFiles(AppDir) then
    begin
      Sleep(1000);
      if AppDirHasLeftoverFiles(AppDir) and (not UninstallSilent) then
        MsgBox(
          'Reclaim removed most of its program files, but some are still in use by another ' +
          'process and could not be deleted:' + #13#10 + #13#10 + AppDir + #13#10#13#10 +
          'Close any other program using Reclaim (or restart your PC), then delete this ' +
          'folder by hand if it still exists.',
          mbInformation, MB_OK
        );
    end;

    // A silent uninstall (/VERYSILENT or /SILENT) has no one to answer a MsgBox — asking would
    // either hang or auto-answer unpredictably, so silent runs always preserve data/ instead,
    // matching this installer's "leave data behind by default" posture end to end.
    if UninstallSilent then
      Exit;

    DataDir := ExpandConstant('{app}\data');
    if DirExists(DataDir) then
    begin
      Response := MsgBox(
        'Reclaim leaves its data folder behind by default (scan history, the quarantine vault, ' +
        'and logs) so you can reinstall without losing anything -- including any files still ' +
        'held in Reclaim''s vault that you have not restored yet.' + #13#10 + #13#10 +
        'Also delete this data folder now?' + #13#10 + #13#10 +
        'Choose No if you are not sure, or if you still have files in the vault you might want ' +
        'back.',
        mbConfirmation, MB_YESNO or MB_DEFBUTTON2
      );
      if Response = IDYES then
        DelTree(DataDir, True, True, True);
    end;
  end;
end;
