; Reclaim installer script (Inno Setup 6/7).
;
; Per-user install, no admin required — matches reclaim.elevation.assert_not_elevated's
; refusal to ever run elevated (this tool must never need, request, or run under UAC
; elevation, at install time or run time). Installs the Nuitka --standalone build produced by
; packaging/build_installer.ps1 into the user's own AppData, and points every shortcut's
; working directory at the install folder itself so reclaim's relative data/ and config.toml
; paths land somewhere the user already owns.

#define MyAppName "Reclaim"
#define MyAppVersion "1.3.0"
#define MyAppPublisher "Gaurav Gandhi"
#define MyAppExeName "reclaim.exe"
#define MyDistDir "build\entry_point.dist"

[Setup]
AppId={{B6C1B6C7-6B6A-4E3B-9B7B-2B7E1E7C6A21}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
DefaultDirName={autopf}\{#MyAppName}
; Per-user default (no admin dialog, no UAC prompt) — matches the "never elevated" invariant.
PrivilegesRequired=lowest
DefaultGroupName={#MyAppName}
DisableProgramGroupPage=yes
OutputBaseFilename=reclaim-setup
OutputDir=dist
Compression=lzma2
SolidCompression=yes
WizardStyle=modern
LicenseFile=..\LICENSE
UninstallDisplayIcon={app}\{#MyAppExeName}
; Brand assets generated by packaging/build_brand_assets.py from the same geometry as
; src/reclaim/api/static/logo.svg — regenerate with `uv run python packaging/build_brand_assets.py`
; if the mark ever changes.
SetupIconFile=reclaim.ico
WizardSmallImageFile=wizard_small.bmp
WizardImageFile=wizard_large.bmp
ArchitecturesAllowed=x64compatible
ArchitecturesInstallIn64BitMode=x64compatible

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "Create a &desktop shortcut"; GroupDescription: "Additional shortcuts:"; Flags: unchecked

[Files]
Source: "{#MyDistDir}\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
; Third-party notices (NOTICES.md) — the dashboard's /NOTICES route reads this relative to the
; process's own working directory ({app}, per the [Icons] "Start in" note below), same pattern
; as the LICENSE-acceptance page's LicenseFile= above needing the repo-root LICENSE at build time.
Source: "..\NOTICES.md"; DestDir: "{app}"; Flags: ignoreversion
; P0-2 fix (2026-08 audit): without this, a fresh install had NO config.toml anywhere and every
; cleanup category shipped enabled=false -- "Clean My Computer" produced zero results, forever,
; with no discoverable fix. Installed as config.toml itself (reclaim.cli's default relative
; path -- see the [Icons] "Start in" note above) so a fresh install gets real default-ON
; categories out of the box. destfilename= renames it on the way in since Source's own basename
; deliberately isn't "config.toml" (that name is gitignored -- see .gitignore's "User's real
; config" entry -- so the repo-tracked source file needs a different name). onlyifdoesntexist:
; an upgrade over an existing install must never clobber a user's already-customized config.toml.
Source: "config.default.toml"; DestDir: "{app}"; DestName: "config.toml"; Flags: onlyifdoesntexist

[Icons]
; "Start in" is deliberately {app} (not {userdocs} or anything else) — reclaim's CLI defaults
; (data/, config.toml, data/mode_log.jsonl) are relative paths, so this is what makes them land
; in the per-user install folder the user already owns, rather than silently landing in
; whatever directory Explorer happened to launch the shortcut from.
Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Parameters: "dashboard"; WorkingDir: "{app}"
Name: "{group}\Uninstall {#MyAppName}"; Filename: "{uninstallexe}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Parameters: "dashboard"; WorkingDir: "{app}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Parameters: "dashboard"; WorkingDir: "{app}"; Description: "Launch {#MyAppName}"; Flags: postinstall nowait skipifsilent unchecked

[Registry]
; R5 (80%-threshold disk-space notification): the toast's Snooze action button uses
; ToastButton(launch="reclaim-notify:snooze-disk-alert"), which Windows resolves via a plain
; ShellExecute against this registered scheme -- no COM "Notification Activator" server needed,
; and it works even though the short-lived scheduled-task process that fired the toast has
; already exited by the time the user clicks it (see src/reclaim/notifications.py's module
; docstring for why protocol activation, not an in-process on_activated callback, is the right
; mechanism here). HKCU (not HKCR/HKLM) needs no admin rights, matching
; PrivilegesRequired=lowest above. `Flags: uninsdeletekey` on the top-level key removes this
; entire subtree (including \shell\open\command below) automatically on uninstall -- no [Code]
; needed for cleanup, unlike the scheduled task registered in [Code] further down.
Root: HKCU; Subkey: "Software\Classes\reclaim-notify"; ValueType: string; ValueName: ""; ValueData: "URL:Reclaim Notification Action"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Classes\reclaim-notify"; ValueType: string; ValueName: "URL Protocol"; ValueData: ""
Root: HKCU; Subkey: "Software\Classes\reclaim-notify\shell\open\command"; ValueType: string; ValueName: ""; ValueData: """{app}\{#MyAppExeName}"" check-disk-space --apply-snooze --config ""{app}\config.toml"" --state ""{app}\data\notification_state.json"""

[Code]
// R5 (80%-threshold disk-space notification): a per-user, non-elevated Task Scheduler entry
// that runs `reclaim check-disk-space` a few times a day -- installed here, removed in
// UnregisterDiskSpaceTask (called from CurUninstallStepChanged below). See
// src/reclaim/notifications.py's module docstring for the feature's own reliability posture
// (opt-in via config.toml, never raises, debounced/snoozable).
const
  DiskSpaceTaskName = 'Reclaim Disk Space Check';

// Minimal escaping for the handful of XML-significant characters that could in principle appear
// in an install path (a username containing '&', for instance) -- {app} and {#MyAppExeName} are
// both interpolated directly into element text below, not attribute values, so only these three
// entities are needed.
function XmlEscape(const S: String): String;
var
  Escaped: String;
begin
  Escaped := S;
  StringChangeEx(Escaped, '&', '&amp;', True);
  StringChangeEx(Escaped, '<', '&lt;', True);
  StringChangeEx(Escaped, '>', '&gt;', True);
  Result := Escaped;
end;

// AY1 (2026-08-24 audit): `SaveStringToFile`'s second parameter is `AnsiString` -- Inno's Pascal
// Script implicitly narrows the Unicode `String` XmlContent to the system ANSI/UTF-8 codepage
// when it's passed there, so the file actually written was always single-byte-per-character
// bytes, never real UTF-16, regardless of what the XML's own `encoding="UTF-16"` declaration
// claimed. Live-reproduced this session: `schtasks.exe /create /xml` genuinely requires real
// UTF-16 content for a task-definition XML -- confirmed by direct testing that neither a bare
// UTF-8 declaration nor a UTF-8 BOM satisfies it ("unable to switch the encoding" / "incorrect
// document syntax" respectively); only actual UTF-16LE bytes with a UTF-16LE BOM work. This
// builds those bytes explicitly (BOM + 2 bytes per source character, low byte first) into an
// AnsiString that SaveStringToFile then writes verbatim -- no further ANSI conversion applies
// once the value is already an AnsiString. Assumes every character in `S` is within the Latin-1
// range (0-255), true for this file's actual content (ASCII XML markup plus a Windows install
// path XmlEscape already sanitizes) -- not a general-purpose UTF-16 encoder.
function Utf16LEBytes(const S: String): AnsiString;
var
  I, Code: Integer;
begin
  Result := Chr($FF) + Chr($FE); // UTF-16LE byte-order mark
  for I := 1 to Length(S) do
  begin
    Code := Ord(S[I]);
    Result := Result + Chr(Code and $FF) + Chr((Code div 256) and $FF);
  end;
end;

procedure RegisterDiskSpaceTask();
var
  ResultCode: Integer;
  ExePath, AppDir, XmlPath, XmlContent: String;
begin
  ExePath := XmlEscape(ExpandConstant('{app}\{#MyAppExeName}'));
  AppDir := XmlEscape(ExpandConstant('{app}'));
  XmlPath := ExpandConstant('{tmp}\reclaim_disk_space_task.xml');

  // Registered via `/xml`, not the simpler `/tr` flag: schtasks caps a plain `/tr` value at 261
  // characters (confirmed by direct reproduction against a real install-path-length command
  // line -- a full "<exe> check-disk-space --config <path> --state <path>" line can realistically
  // exceed that with a typical per-user install path), and `/tr` has no equivalent to
  // <WorkingDirectory> either. Using WorkingDirectory here means the scheduled invocation reuses
  // reclaim's normal relative config.toml/data/ paths, exactly like the Start Menu shortcut's own
  // "Start in {app}" (see the [Icons] section above) -- no --config/--state override needed for
  // the periodic check itself (unlike the Snooze protocol handler in [Registry] above, which has
  // no working-directory concept and so needs the explicit absolute paths there).
  //
  // A LogonType of InteractiveToken with no RunLevel element (defaults to LeastPrivilege) is a
  // per-user task that runs only while this user is logged on, needs no stored password, and
  // never elevates -- matching PrivilegesRequired=lowest above and this project's own
  // never-run-elevated invariant (reclaim.elevation.assert_not_elevated).
  //
  // The StartBoundary below is a fixed date in the past, intentionally: confirmed by direct
  // reproduction (schtasks /query /v against a task created with this exact XML shape) that Task
  // Scheduler computes the next occurrence from the repetition pattern (StartBoundary + N *
  // Interval, the smallest N at or after now), not by "catching up" on every missed interval
  // since the literal boundary date -- so this never fires a burst of overdue runs at install
  // time, regardless of how long ago the boundary date is.
  // AY1 (2026-08-24 audit): live-reproduced -- this declares "UTF-16" but SaveStringToFile's
  // AnsiString parameter meant the file actually written was single-byte-per-character bytes
  // (confirmed by inspecting the real bytes written during a real install: the file starts
  // `3C 3F 78 6D 6C` -- '<?xml' in single-byte form -- not the UTF-16LE `3C 00 3F 00...` a
  // genuine UTF-16 file, or any BOM). This mismatch made `schtasks.exe /create /xml` fail
  // outright (ResultCode 1) on EVERY install this feature has ever shipped in, confirmed across
  // 11 of 12 real trip runs in this engagement's own history hitting this exact "task not
  // found" symptom. Also confirmed by direct testing that this ISN'T fixable by just declaring
  // a different encoding while still writing single-byte bytes: neither a bare UTF-8
  // declaration ("ERROR: unable to switch the encoding") nor a UTF-8 BOM ("ERROR: incorrect
  // document syntax") satisfies `schtasks /xml` -- it genuinely requires real UTF-16LE content.
  // Fixed at the WRITE side instead (`Utf16LEBytes` above, used below) -- this declaration was
  // always correct, the bytes just never matched it. Verified by direct reproduction: real
  // `schtasks /create` now succeeds and the task is genuinely present afterward.
  XmlContent :=
    '<?xml version="1.0" encoding="UTF-16"?>' + #13#10 +
    '<Task version="1.2" xmlns="http://schemas.microsoft.com/windows/2004/02/mit/task">' + #13#10 +
    '  <RegistrationInfo>' + #13#10 +
    '    <Description>Reclaim: periodic disk-space threshold check (fires a toast if crossed; ' +
      'see PRIVACY.md).</Description>' + #13#10 +
    '  </RegistrationInfo>' + #13#10 +
    '  <Triggers>' + #13#10 +
    '    <TimeTrigger>' + #13#10 +
    '      <Repetition>' + #13#10 +
    '        <Interval>PT4H</Interval>' + #13#10 +
    '        <StopAtDurationEnd>false</StopAtDurationEnd>' + #13#10 +
    '      </Repetition>' + #13#10 +
    '      <StartBoundary>2026-01-01T09:00:00</StartBoundary>' + #13#10 +
    '      <Enabled>true</Enabled>' + #13#10 +
    '    </TimeTrigger>' + #13#10 +
    '  </Triggers>' + #13#10 +
    '  <Principals>' + #13#10 +
    '    <Principal id="Author">' + #13#10 +
    '      <LogonType>InteractiveToken</LogonType>' + #13#10 +
    '    </Principal>' + #13#10 +
    '  </Principals>' + #13#10 +
    '  <Settings>' + #13#10 +
    '    <MultipleInstancesPolicy>IgnoreNew</MultipleInstancesPolicy>' + #13#10 +
    '    <DisallowStartIfOnBatteries>false</DisallowStartIfOnBatteries>' + #13#10 +
    '    <StopIfGoingOnBatteries>false</StopIfGoingOnBatteries>' + #13#10 +
    '    <StartWhenAvailable>true</StartWhenAvailable>' + #13#10 +
    '    <RunOnlyIfNetworkAvailable>false</RunOnlyIfNetworkAvailable>' + #13#10 +
    '    <ExecutionTimeLimit>PT2M</ExecutionTimeLimit>' + #13#10 +
    '  </Settings>' + #13#10 +
    '  <Actions Context="Author">' + #13#10 +
    '    <Exec>' + #13#10 +
    '      <Command>' + ExePath + '</Command>' + #13#10 +
    '      <Arguments>check-disk-space</Arguments>' + #13#10 +
    '      <WorkingDirectory>' + AppDir + '</WorkingDirectory>' + #13#10 +
    '    </Exec>' + #13#10 +
    '  </Actions>' + #13#10 +
    '</Task>';

  SaveStringToFile(XmlPath, Utf16LEBytes(XmlContent), False);
  // /F overwrites a pre-existing task from an earlier install (reinstall/upgrade must not fail
  // or duplicate the trigger) -- same idempotent-reinstall posture InitializeUninstall's
  // taskkill already applies to process termination. A failure here (schtasks missing/disabled,
  // an unusual locked-down environment) is not surfaced -- this is a best-effort convenience
  // registration, not a required install step; the dashboard/CLI work identically without it,
  // just without the background check.
  //
  // One retry after a short wait: schtasks against a just-written file can plausibly race a
  // real-time AV scan of a large, freshly-extracted install tree (the same class of hazard
  // InitializeUninstall's own Sleep(500) already guards against elsewhere in this script) --
  // cheap insurance, still best-effort either way. NOT a fix for AY1's actual root cause above
  // (that was the encoding bug, confirmed structurally); this retry is a separate, general
  // defensive measure, not verified against a real failure of this specific kind.
  Exec('schtasks.exe', '/create /tn "' + DiskSpaceTaskName + '" /xml "' + XmlPath + '" /f',
    '', SW_HIDE, ewWaitUntilTerminated, ResultCode);
  if ResultCode <> 0 then
  begin
    Sleep(1500);
    Exec('schtasks.exe', '/create /tn "' + DiskSpaceTaskName + '" /xml "' + XmlPath + '" /f',
      '', SW_HIDE, ewWaitUntilTerminated, ResultCode);
  end;
  DeleteFile(XmlPath);
end;

procedure UnregisterDiskSpaceTask();
var
  ResultCode: Integer;
begin
  // A nonzero exit (task never existed -- e.g. an install that predates this feature, or a user
  // who manually removed it) is not surfaced -- same "don't fail the uninstall over a
  // best-effort cleanup step" posture as the rest of this script.
  Exec('schtasks.exe', '/delete /tn "' + DiskSpaceTaskName + '" /f',
    '', SW_HIDE, ewWaitUntilTerminated, ResultCode);
end;

procedure CurStepChanged(CurStep: TSetupStep);
begin
  // ssPostInstall fires after [Files] has finished copying, so {app}\{#MyAppExeName} already
  // exists by the time schtasks' <Command> element is registered against it.
  if CurStep = ssPostInstall then
    RegisterDiskSpaceTask();
end;

// fix/uninstaller-terminate-running-process: a Reclaim server process (the dashboard, or a
// background scan/apply/AI-analysis worker it spawned) holds an OS-level lock on reclaim.exe
// and its loaded DLLs for as long as it's running. Inno's own [Files] removal pass can't clear
// that lock, and used to fail SILENTLY on each locked file rather than aborting the uninstall
// -- Add/Remove Programs correctly reported the app gone (registry entry + shortcuts removed)
// while ~30 program files, still holding real locks, survived on disk. Observed for real: a
// scan-worker process outlived a killed parent and kept writing to data\logs\reclaim.log for
// a full minute after the uninstaller's file-removal pass had already run past it.
//
// InitializeUninstall is the very first thing Inno calls, before any removal begins -- killing
// the process tree here, not at usUninstall's start, means the removal pass itself never has to
// contend with a live process at all.
function InitializeUninstall(): Boolean;
var
  ResultCode: Integer;
begin
  Result := True;
  // /T also kills child processes of the tree (a scan/AI worker spawned via multiprocessing)
  // -- killing only the top-level dashboard process and leaving a worker running is exactly
  // the incident above. /F force-terminates; taskkill exits 0 (killed) or 128 (nothing was
  // running, not an error) -- neither is worth surfacing, and this never needs admin rights to
  // kill a process the current non-elevated user already owns (this installer is always
  // per-user/non-elevated -- see PrivilegesRequired=lowest above).
  Exec('taskkill.exe', '/F /T /IM {#MyAppExeName}', '', SW_HIDE, ewWaitUntilTerminated, ResultCode);
  // Windows releases a terminated process's file handles as part of process teardown, which is
  // prompt but not guaranteed synchronous with taskkill.exe's own exit -- and a freshly-freed
  // reclaim.exe is exactly the kind of file Defender's real-time scanner re-locks transiently
  // right after a process release it (see packaging/RELEASE_RUNBOOK.md's cold-start scan note).
  // A short wait here is cheap insurance against exactly that race.
  Sleep(500);
end;

// Directory enumeration helper for the leftover-file check in CurUninstallStepChanged below --
// True if {app} contains anything other than `data\` (which the [Files] section never lists,
// so Inno's own removal pass never touches it -- see the data-folder-preservation comment
// further down). A non-empty result here means InitializeUninstall's taskkill above didn't
// fully do its job.
function AppDirHasLeftoverFiles(AppDir: String): Boolean;
var
  FindRec: TFindRec;
begin
  Result := False;
  if FindFirst(AppDir + '\*', FindRec) then
  begin
    try
      repeat
        if (FindRec.Name <> '.') and (FindRec.Name <> '..') and (FindRec.Name <> 'data') then
          Result := True;
      until (not FindNext(FindRec)) or Result;
    finally
      FindClose(FindRec);
    end;
  end;
end;

// Reclaim's data (scan index, quarantine vault, mode/apply logs — see the [Icons] comment above
// for why these are relative paths under {app}\data) survives a normal uninstall by default: the
// [Files] section above only ever lists the Nuitka --standalone build output, never {app}\data,
// so Inno Setup's own file-removal pass never touches it. This handler adds the explicit,
// opt-in "also delete my data" step GG's uninstall spec calls for, asked only after the program
// files are already gone (usPostUninstall) so a Cancel/No leaves a fully-working, reinstallable
// data folder behind.
procedure CurUninstallStepChanged(CurUninstallStep: TUninstallStep);
var
  DataDir: String;
  AppDir: String;
  Response: Integer;
begin
  if CurUninstallStep = usUninstall then
    // R5: remove the per-user scheduled task registered by RegisterDiskSpaceTask above. Run at
    // usUninstall (before file removal / the data-folder prompt below) rather than
    // usPostUninstall -- no ordering dependency on either, but this keeps "undo everything this
    // installer registered outside of {app} itself" together as one step, matching
    // InitializeUninstall's own "do the OS-level cleanup first" shape. The [Registry] protocol
    // handler needs no equivalent call here -- Flags: uninsdeletekey in [Registry] above already
    // removes it automatically.
    UnregisterDiskSpaceTask();

  if CurUninstallStep = usPostUninstall then
  begin
    // Defensive verification, not the primary fix (InitializeUninstall's taskkill above is):
    // confirm the removal pass this step follows actually left {app} clean. One retry after a
    // short wait covers a transient re-lock (e.g. Defender); if it's STILL not clean after
    // that, say so plainly instead of leaving silent orphans with no signal at all -- the
    // original bug this whole change fixes.
    AppDir := ExpandConstant('{app}');
    if AppDirHasLeftoverFiles(AppDir) then
    begin
      Sleep(1000);
      if AppDirHasLeftoverFiles(AppDir) and (not UninstallSilent) then
        MsgBox(
          'Reclaim removed most of its program files, but some are still in use by another ' +
          'process and could not be deleted:' + #13#10 + #13#10 + AppDir + #13#10#13#10 +
          'Close any other program using Reclaim (or restart your PC), then delete this ' +
          'folder by hand if it still exists.',
          mbInformation, MB_OK
        );
    end;

    // A silent uninstall (/VERYSILENT or /SILENT) has no one to answer a MsgBox — asking would
    // either hang or auto-answer unpredictably, so silent runs always preserve data/ instead,
    // matching this installer's "leave data behind by default" posture end to end.
    if UninstallSilent then
      Exit;

    DataDir := ExpandConstant('{app}\data');
    if DirExists(DataDir) then
    begin
      Response := MsgBox(
        'Reclaim leaves its data folder behind by default (scan history, the quarantine vault, ' +
        'and logs) so you can reinstall without losing anything -- including any files still ' +
        'held in Reclaim''s vault that you have not restored yet.' + #13#10 + #13#10 +
        'Also delete this data folder now?' + #13#10 + #13#10 +
        'Choose No if you are not sure, or if you still have files in the vault you might want ' +
        'back.',
        mbConfirmation, MB_YESNO or MB_DEFBUTTON2
      );
      if Response = IDYES then
        DelTree(DataDir, True, True, True);
    end;
  end;
end;
