; Reclaim installer script (Inno Setup 6/7).
;
; Per-user install, no admin required — matches reclaim.elevation.assert_not_elevated's
; refusal to ever run elevated (this tool must never need, request, or run under UAC
; elevation, at install time or run time). Installs the Nuitka --standalone build produced by
; packaging/build_installer.ps1 into the user's own AppData, and points every shortcut's
; working directory at the install folder itself so reclaim's relative data/ and config.toml
; paths land somewhere the user already owns.

#define MyAppName "Reclaim"
#define MyAppVersion "1.3.0"
#define MyAppPublisher "Gaurav Gandhi"
#define MyAppExeName "reclaim.exe"
#define MyDistDir "build\entry_point.dist"

[Setup]
AppId={{B6C1B6C7-6B6A-4E3B-9B7B-2B7E1E7C6A21}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
DefaultDirName={autopf}\{#MyAppName}
; Per-user default (no admin dialog, no UAC prompt) — matches the "never elevated" invariant.
PrivilegesRequired=lowest
DefaultGroupName={#MyAppName}
DisableProgramGroupPage=yes
OutputBaseFilename=reclaim-setup
OutputDir=dist
Compression=lzma2
SolidCompression=yes
WizardStyle=modern
LicenseFile=..\LICENSE
UninstallDisplayIcon={app}\{#MyAppExeName}
; Brand assets generated by packaging/build_brand_assets.py from the same geometry as
; src/reclaim/api/static/logo.svg — regenerate with `uv run python packaging/build_brand_assets.py`
; if the mark ever changes.
SetupIconFile=reclaim.ico
WizardSmallImageFile=wizard_small.bmp
WizardImageFile=wizard_large.bmp
ArchitecturesAllowed=x64compatible
ArchitecturesInstallIn64BitMode=x64compatible

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "Create a &desktop shortcut"; GroupDescription: "Additional shortcuts:"; Flags: unchecked

[Files]
Source: "{#MyDistDir}\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
; Third-party notices (NOTICES.md) — the dashboard's /NOTICES route reads this relative to the
; process's own working directory ({app}, per the [Icons] "Start in" note below), same pattern
; as the LICENSE-acceptance page's LicenseFile= above needing the repo-root LICENSE at build time.
Source: "..\NOTICES.md"; DestDir: "{app}"; Flags: ignoreversion
; P0-2 fix (2026-08 audit): without this, a fresh install had NO config.toml anywhere and every
; cleanup category shipped enabled=false -- "Clean My Computer" produced zero results, forever,
; with no discoverable fix. Installed as config.toml itself (reclaim.cli's default relative
; path -- see the [Icons] "Start in" note above) so a fresh install gets real default-ON
; categories out of the box. destfilename= renames it on the way in since Source's own basename
; deliberately isn't "config.toml" (that name is gitignored -- see .gitignore's "User's real
; config" entry -- so the repo-tracked source file needs a different name). onlyifdoesntexist:
; an upgrade over an existing install must never clobber a user's already-customized config.toml.
Source: "config.default.toml"; DestDir: "{app}"; DestName: "config.toml"; Flags: onlyifdoesntexist

[Icons]
; "Start in" is deliberately {app} (not {userdocs} or anything else) — reclaim's CLI defaults
; (data/, config.toml, data/mode_log.jsonl) are relative paths, so this is what makes them land
; in the per-user install folder the user already owns, rather than silently landing in
; whatever directory Explorer happened to launch the shortcut from.
Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Parameters: "dashboard"; WorkingDir: "{app}"
Name: "{group}\Uninstall {#MyAppName}"; Filename: "{uninstallexe}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Parameters: "dashboard"; WorkingDir: "{app}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Parameters: "dashboard"; WorkingDir: "{app}"; Description: "Launch {#MyAppName}"; Flags: postinstall nowait skipifsilent unchecked

[Registry]
; R5 (80%-threshold disk-space notification): the toast's Snooze action button uses
; ToastButton(launch="reclaim-notify:snooze-disk-alert"), which Windows resolves via a plain
; ShellExecute against this registered scheme -- no COM "Notification Activator" server needed,
; and it works even though the short-lived scheduled-task process that fired the toast has
; already exited by the time the user clicks it (see src/reclaim/notifications.py's module
; docstring for why protocol activation, not an in-process on_activated callback, is the right
; mechanism here). HKCU (not HKCR/HKLM) needs no admin rights, matching
; PrivilegesRequired=lowest above. `Flags: uninsdeletekey` on the top-level key removes this
; entire subtree (including \shell\open\command below) automatically on uninstall -- no [Code]
; needed for cleanup, unlike the scheduled task registered in [Code] further down.
Root: HKCU; Subkey: "Software\Classes\reclaim-notify"; ValueType: string; ValueName: ""; ValueData: "URL:Reclaim Notification Action"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Classes\reclaim-notify"; ValueType: string; ValueName: "URL Protocol"; ValueData: ""
Root: HKCU; Subkey: "Software\Classes\reclaim-notify\shell\open\command"; ValueType: string; ValueName: ""; ValueData: """{app}\{#MyAppExeName}"" check-disk-space --apply-snooze --config ""{app}\config.toml"" --state ""{app}\data\notification_state.json"""

[Code]
// R5 (80%-threshold disk-space notification): a per-user, non-elevated Task Scheduler entry
// that runs `reclaim check-disk-space` a few times a day -- installed here, removed in
// UnregisterDiskSpaceTask (called from CurUninstallStepChanged below). See
// src/reclaim/notifications.py's module docstring for the feature's own reliability posture
// (opt-in via config.toml, never raises, debounced/snoozable).
//
// BE1 (2026-08-26 audit): BD1 only made the machine-wide-namespace collision this name caused
// LOUD (a diagnostic log file), not fixed -- on a real multi-account PC the second, non-admin
// account's alert would still silently never register, permanently, unless that user happened
// to go looking for a diagnostic file they have no reason to expect exists. Fixed for real:
// LegacyDiskSpaceTaskName is kept only so RegisterDiskSpaceTask can clean up a pre-BE1 install's
// task (best-effort, see below) -- every NEW registration uses GetDiskSpaceTaskName() instead,
// which embeds the current Windows username, so two accounts can never collide in the shared
// machine-wide Task Scheduler namespace again, by construction, regardless of install order.
const
  LegacyDiskSpaceTaskName = 'Reclaim Disk Space Check';

function GetDiskSpaceTaskName(): String;
begin
  Result := 'Reclaim Disk Space Check (' + ExpandConstant('{username}') + ')';
end;

// Minimal escaping for the handful of XML-significant characters that could in principle appear
// in an install path (a username containing '&', for instance) -- {app} and {#MyAppExeName} are
// both interpolated directly into element text below, not attribute values, so only these three
// entities are needed.
function XmlEscape(const S: String): String;
var
  Escaped: String;
begin
  Escaped := S;
  StringChangeEx(Escaped, '&', '&amp;', True);
  StringChangeEx(Escaped, '<', '&lt;', True);
  StringChangeEx(Escaped, '>', '&gt;', True);
  Result := Escaped;
end;

// AY1 (2026-08-24 audit): `SaveStringToFile`'s second parameter is `AnsiString` -- Inno's Pascal
// Script implicitly narrows the Unicode `String` XmlContent to the system ANSI/UTF-8 codepage
// when it's passed there, so the file actually written was always single-byte-per-character
// bytes, never real UTF-16, regardless of what the XML's own `encoding="UTF-16"` declaration
// claimed. Live-reproduced this session: `schtasks.exe /create /xml` genuinely requires real
// UTF-16 content for a task-definition XML -- confirmed by direct testing that neither a bare
// UTF-8 declaration nor a UTF-8 BOM satisfies it ("unable to switch the encoding" / "incorrect
// document syntax" respectively); only actual UTF-16LE bytes with a UTF-16LE BOM work. This
// builds those bytes explicitly (BOM + 2 bytes per source character, low byte first) into an
// AnsiString that SaveStringToFile then writes verbatim -- no further ANSI conversion applies
// once the value is already an AnsiString. Assumes every character in `S` is within the Latin-1
// range (0-255), true for this file's actual content (ASCII XML markup plus a Windows install
// path XmlEscape already sanitizes) -- not a general-purpose UTF-16 encoder.
function Utf16LEBytes(const S: String): AnsiString;
var
  I, Code: Integer;
begin
  Result := Chr($FF) + Chr($FE); // UTF-16LE byte-order mark
  for I := 1 to Length(S) do
  begin
    Code := Ord(S[I]);
    Result := Result + Chr(Code and $FF) + Chr((Code div 256) and $FF);
  end;
end;

// BD1 (2026-08-26 audit): live-reproduced -- root-caused why a real ReclaimSmokeTest trip hit
// "Task 'Reclaim Disk Space Check' not found" even though this exact binary's AY1 fix (the
// UTF-16 encoding above) is confirmed present and confirmed WORKING when the identical install
// runs under a different account (gaura's own dev account: task registered, LastResult=0, a
// real scheduled fire succeeded). The difference is not the binary -- it's that Task Scheduler's
// root folder is one machine-wide namespace: a task NAME is unique per machine, not per user.
// This dev machine already had "Reclaim Disk Space Check" registered under gaura (a prior
// verification install), and `icacls "C:\Windows\System32\Tasks\Reclaim Disk Space Check"`
// confirms its DACL grants write/delete only to gaura, Administrators, and SYSTEM -- a second,
// different, non-admin account (ReclaimSmokeTest) has ZERO rights on that task object, so its own
// `/create ... /f` cannot overwrite it and fails with access denied, silently, every time,
// deterministically -- not a race, not machine-local corruption of the kind AY1's original retry
// logic was written to tolerate. This is a real product-facing gap too, not just a test-rig
// artifact: any real multi-account Windows PC where a second (non-admin) user installs Reclaim
// after a first user already did will hit the identical silent failure. Not fixed at the
// namespace level in this pass (a per-user task name would be a larger behavior change, e.g.
// losing the single predictable task name UnregisterDiskSpaceTask/support docs rely on) --
// fixed by making the failure loud instead of swallowed, per the actual ask: every attempt now
// writes its real exit code and captured schtasks output to a durable, always-present log file
// (success or failure), so this stops being invisible.
const
  TaskDiagLogName = 'task_registration_diagnostic.log';

// Runs `schtasks.exe /create /xml ... /f` via cmd.exe with real stdout+stderr redirection --
// Inno's own `Exec` gives only a process exit code, never captured output, and schtasks writes
// its actual error text ("ERROR: Access is denied", "ERROR: Invalid Xml...") to stdout, not just
// a bare exit code -- redirection is the only way to capture the text a human (or a future
// diagnostic reader) needs to distinguish "access denied by another account's task" from any
// other failure shape.
function RunSchtasksCreateCaptured(const TaskName, XmlPath: String; var ResultCode: Integer): String;
var
  CmdLine, CapturePath, Output: String;
  Lines: TArrayOfString;
  I: Integer;
begin
  CapturePath := ExpandConstant('{tmp}\schtasks_create_output.txt');
  CmdLine := '/c schtasks.exe /create /tn "' + TaskName + '" /xml "' + XmlPath +
    '" /f > "' + CapturePath + '" 2>&1';
  Exec('cmd.exe', CmdLine, '', SW_HIDE, ewWaitUntilTerminated, ResultCode);
  Output := '';
  if LoadStringsFromFile(CapturePath, Lines) then
  begin
    for I := 0 to GetArrayLength(Lines) - 1 do
      Output := Output + Lines[I] + #13#10;
  end;
  DeleteFile(CapturePath);
  Result := Output;
end;

// BM3 (2026-08-26 audit) fix for BL6: reads a task's currently-registered <Command> element via
// `schtasks /query /xml`, without any real XML parser -- a plain substring check against the
// exact "<Command>...</Command>" shape RegisterDiskSpaceTask itself always writes is sufficient
// for one well-known element. Returns '' if the task doesn't exist at all (nothing registered,
// or query failed) -- callers treat that as "no owner to protect/match against", not an error.
function GetRegisteredTaskCommandPath(const TaskName: String): String;
var
  ResultCode: Integer;
  CmdLine, CapturePath, Output, StartTag, EndTag: String;
  Lines: TArrayOfString;
  I, StartPos, EndPos: Integer;
begin
  Result := '';
  CapturePath := ExpandConstant('{tmp}\schtasks_query_output.txt');
  CmdLine := '/c schtasks.exe /query /tn "' + TaskName + '" /xml > "' + CapturePath + '" 2>&1';
  Exec('cmd.exe', CmdLine, '', SW_HIDE, ewWaitUntilTerminated, ResultCode);
  if ResultCode <> 0 then
  begin
    DeleteFile(CapturePath);
    Exit;
  end;
  Output := '';
  if LoadStringsFromFile(CapturePath, Lines) then
  begin
    for I := 0 to GetArrayLength(Lines) - 1 do
      Output := Output + Lines[I] + #13#10;
  end;
  DeleteFile(CapturePath);
  StartTag := '<Command>';
  EndTag := '</Command>';
  StartPos := Pos(StartTag, Output);
  if StartPos = 0 then
    Exit;
  StartPos := StartPos + Length(StartTag);
  EndPos := Pos(EndTag, Output);
  if (EndPos = 0) or (EndPos <= StartPos) then
    Exit;
  Result := Copy(Output, StartPos, EndPos - StartPos);
end;

procedure RegisterDiskSpaceTask();
var
  ResultCode: Integer;
  ExePath, AppDir, XmlPath, XmlContent, DiagPath, Output, Summary, TaskName, MigrationNote: String;
  Attempt: Integer;
  ExistingOwnerPath: String;
begin
  TaskName := GetDiskSpaceTaskName();
  ExePath := XmlEscape(ExpandConstant('{app}\{#MyAppExeName}'));
  AppDir := XmlEscape(ExpandConstant('{app}'));
  XmlPath := ExpandConstant('{tmp}\reclaim_disk_space_task.xml');

  // BM3 (2026-08-26 audit) fix for BL6: reproduced live, twice -- a second install for the same
  // account (e.g. a scratch install to a different directory) used to silently OVERWRITE
  // (schtasks /f) an existing, still-valid install's task registration, because the task name is
  // per-account, not per-install-directory. If a task already exists under this name, points at
  // a DIFFERENT exe path, and that other exe still exists on disk (i.e. that install is still
  // genuinely present, not orphaned), skip registration here entirely rather than stealing it --
  // the other install's alert keeps working, and this install simply doesn't get a background
  // check registered (same "best-effort, not required" posture as every other failure path in
  // this procedure). An orphaned reference (the other path no longer exists -- that install was
  // removed some other way, e.g. a manual folder delete) is not "still remaining" and does not
  // block this registration.
  ExistingOwnerPath := GetRegisteredTaskCommandPath(TaskName);
  if (ExistingOwnerPath <> '') and (ExistingOwnerPath <> ExePath) and FileExists(ExistingOwnerPath) then
  begin
    DiagPath := ExpandConstant('{app}\data\') + TaskDiagLogName;
    ForceDirectories(ExpandConstant('{app}\data'));
    SaveStringToFile(DiagPath,
      'Reclaim disk-space task registration -- ' + GetDateTimeString('yyyy-mm-dd hh:nn:ss', '-', ':') + #13#10 +
      'RESULT: SKIPPED -- task "' + TaskName + '" is already registered and owned by a different, ' +
      'still-present install at "' + ExistingOwnerPath + '". Not overwriting it (BM3, 2026-08-26 ' +
      'audit -- overwriting used to silently steal the task from that install). This install''s ' +
      'own background disk-space alert is not registered; the other install''s alert is unaffected ' +
      'and continues to work.' + #13#10, False);
    Exit;
  end;

  // BE1: best-effort cleanup of a pre-BE1 install's task under the old shared fixed name --
  // succeeds (and removes the duplicate/orphan) when THIS account created it on an earlier
  // install; silently fails (does nothing, harmlessly) when it doesn't exist or belongs to a
  // different account, exactly the same posture as every other best-effort step in this
  // procedure. Not gated on ResultCode -- deleting something that isn't there, or that this
  // account doesn't own, is not a failure worth reacting to.
  Exec('schtasks.exe', '/delete /tn "' + LegacyDiskSpaceTaskName + '" /f',
    '', SW_HIDE, ewWaitUntilTerminated, ResultCode);
  if ResultCode = 0 then
    MigrationNote := 'Removed a pre-existing legacy-named task ("' + LegacyDiskSpaceTaskName +
      '") owned by this account -- migrated to the per-account name below.' + #13#10
  else
    MigrationNote := '';

  // Registered via `/xml`, not the simpler `/tr` flag: schtasks caps a plain `/tr` value at 261
  // characters (confirmed by direct reproduction against a real install-path-length command
  // line -- a full "<exe> check-disk-space --config <path> --state <path>" line can realistically
  // exceed that with a typical per-user install path), and `/tr` has no equivalent to
  // <WorkingDirectory> either. Using WorkingDirectory here means the scheduled invocation reuses
  // reclaim's normal relative config.toml/data/ paths, exactly like the Start Menu shortcut's own
  // "Start in {app}" (see the [Icons] section above) -- no --config/--state override needed for
  // the periodic check itself (unlike the Snooze protocol handler in [Registry] above, which has
  // no working-directory concept and so needs the explicit absolute paths there).
  //
  // A LogonType of InteractiveToken with no RunLevel element (defaults to LeastPrivilege) is a
  // per-user task that runs only while this user is logged on, needs no stored password, and
  // never elevates -- matching PrivilegesRequired=lowest above and this project's own
  // never-run-elevated invariant (reclaim.elevation.assert_not_elevated).
  //
  // The StartBoundary below is a fixed date in the past, intentionally: confirmed by direct
  // reproduction (schtasks /query /v against a task created with this exact XML shape) that Task
  // Scheduler computes the next occurrence from the repetition pattern (StartBoundary + N *
  // Interval, the smallest N at or after now), not by "catching up" on every missed interval
  // since the literal boundary date -- so this never fires a burst of overdue runs at install
  // time, regardless of how long ago the boundary date is.
  // AY1 (2026-08-24 audit): live-reproduced -- this declares "UTF-16" but SaveStringToFile's
  // AnsiString parameter meant the file actually written was single-byte-per-character bytes
  // (confirmed by inspecting the real bytes written during a real install: the file starts
  // `3C 3F 78 6D 6C` -- '<?xml' in single-byte form -- not the UTF-16LE `3C 00 3F 00...` a
  // genuine UTF-16 file, or any BOM). This mismatch made `schtasks.exe /create /xml` fail
  // outright (ResultCode 1) on EVERY install this feature has ever shipped in, confirmed across
  // 11 of 12 real trip runs in this engagement's own history hitting this exact "task not
  // found" symptom. Also confirmed by direct testing that this ISN'T fixable by just declaring
  // a different encoding while still writing single-byte bytes: neither a bare UTF-8
  // declaration ("ERROR: unable to switch the encoding") nor a UTF-8 BOM ("ERROR: incorrect
  // document syntax") satisfies `schtasks /xml` -- it genuinely requires real UTF-16LE content.
  // Fixed at the WRITE side instead (`Utf16LEBytes` above, used below) -- this declaration was
  // always correct, the bytes just never matched it. Verified by direct reproduction: real
  // `schtasks /create` now succeeds and the task is genuinely present afterward.
  XmlContent :=
    '<?xml version="1.0" encoding="UTF-16"?>' + #13#10 +
    '<Task version="1.2" xmlns="http://schemas.microsoft.com/windows/2004/02/mit/task">' + #13#10 +
    '  <RegistrationInfo>' + #13#10 +
    '    <Description>Reclaim: periodic disk-space threshold check (fires a toast if crossed; ' +
      'see PRIVACY.md).</Description>' + #13#10 +
    '  </RegistrationInfo>' + #13#10 +
    '  <Triggers>' + #13#10 +
    '    <TimeTrigger>' + #13#10 +
    '      <Repetition>' + #13#10 +
    '        <Interval>PT4H</Interval>' + #13#10 +
    '        <StopAtDurationEnd>false</StopAtDurationEnd>' + #13#10 +
    '      </Repetition>' + #13#10 +
    '      <StartBoundary>2026-01-01T09:00:00</StartBoundary>' + #13#10 +
    '      <Enabled>true</Enabled>' + #13#10 +
    '    </TimeTrigger>' + #13#10 +
    '  </Triggers>' + #13#10 +
    '  <Principals>' + #13#10 +
    '    <Principal id="Author">' + #13#10 +
    '      <LogonType>InteractiveToken</LogonType>' + #13#10 +
    '    </Principal>' + #13#10 +
    '  </Principals>' + #13#10 +
    '  <Settings>' + #13#10 +
    '    <MultipleInstancesPolicy>IgnoreNew</MultipleInstancesPolicy>' + #13#10 +
    '    <DisallowStartIfOnBatteries>false</DisallowStartIfOnBatteries>' + #13#10 +
    '    <StopIfGoingOnBatteries>false</StopIfGoingOnBatteries>' + #13#10 +
    '    <StartWhenAvailable>true</StartWhenAvailable>' + #13#10 +
    '    <RunOnlyIfNetworkAvailable>false</RunOnlyIfNetworkAvailable>' + #13#10 +
    '    <ExecutionTimeLimit>PT2M</ExecutionTimeLimit>' + #13#10 +
    '  </Settings>' + #13#10 +
    '  <Actions Context="Author">' + #13#10 +
    '    <Exec>' + #13#10 +
    '      <Command>' + ExePath + '</Command>' + #13#10 +
    '      <Arguments>check-disk-space</Arguments>' + #13#10 +
    '      <WorkingDirectory>' + AppDir + '</WorkingDirectory>' + #13#10 +
    '    </Exec>' + #13#10 +
    '  </Actions>' + #13#10 +
    '</Task>';

  SaveStringToFile(XmlPath, Utf16LEBytes(XmlContent), False);
  // /F overwrites a pre-existing task from an earlier install (reinstall/upgrade must not fail
  // or duplicate the trigger) -- same idempotent-reinstall posture InitializeUninstall's
  // taskkill already applies to process termination. This is still a best-effort convenience
  // registration, not a required install step -- the dashboard/CLI work identically without it,
  // just without the background check -- but as of BD1 (2026-08-26 audit) a failure is no longer
  // silently discarded: the real exit code and captured schtasks output are always written to
  // {app}\data\task_registration_diagnostic.log below, success or failure.
  //
  // One retry after a short wait: schtasks against a just-written file can plausibly race a
  // real-time AV scan of a large, freshly-extracted install tree (the same class of hazard
  // InitializeUninstall's own Sleep(500) already guards against elsewhere in this script) --
  // cheap insurance. NOT a fix for AY1's original root cause (the encoding bug, confirmed
  // structurally) or for BD1's ACL-collision root cause above (a retry changes nothing about a
  // permissions denial) -- kept only because it's free and does catch a genuine transient race.
  Output := RunSchtasksCreateCaptured(TaskName, XmlPath, ResultCode);
  Attempt := 1;
  if ResultCode <> 0 then
  begin
    Sleep(1500);
    Attempt := 2;
    Output := RunSchtasksCreateCaptured(TaskName, XmlPath, ResultCode);
  end;
  DeleteFile(XmlPath);

  DiagPath := ExpandConstant('{app}\data\') + TaskDiagLogName;
  ForceDirectories(ExpandConstant('{app}\data'));
  if ResultCode = 0 then
    Summary := 'RESULT: SUCCESS (attempt ' + IntToStr(Attempt) + ', exit code 0), task name "' +
      TaskName + '"' + #13#10
  else if Pos('Access is denied', Output) > 0 then
    // BE1: per-account task naming (below) is designed to make this branch unreachable for the
    // ORIGINAL BD1 cause (two different accounts can no longer target the same task name) --
    // retained, not deleted, because "access is denied" from schtasks can still have other
    // causes (a locked-down/managed environment restricting Task Scheduler outright) and this
    // message is still the right shape for those, just no longer able to name BD1 specifically
    // as the likely cause the way it used to.
    Summary := 'RESULT: FAILED (attempt ' + IntToStr(Attempt) + ', exit code ' +
      IntToStr(ResultCode) + ') -- ACCESS DENIED registering "' + TaskName + '". This is no ' +
      'longer expected to be a same-name collision with another account (BE1, 2026-08-26 audit: ' +
      'the task name now embeds this account''s own username) -- more likely a locked-down or ' +
      'managed environment restricting Task Scheduler access outright. The background disk-space ' +
      'alert is disabled for this account; everything else in Reclaim works normally.' + #13#10
  else
    Summary := 'RESULT: FAILED (attempt ' + IntToStr(Attempt) + ', exit code ' +
      IntToStr(ResultCode) + ') -- see captured output below. The background disk-space alert ' +
      'is disabled for this account; everything else in Reclaim works normally.' + #13#10;
  SaveStringToFile(DiagPath,
    'Reclaim disk-space task registration -- ' + GetDateTimeString('yyyy-mm-dd hh:nn:ss', '-', ':') + #13#10 +
    MigrationNote + Summary + #13#10 + 'Captured schtasks output:' + #13#10 + Output, False);
end;

procedure UnregisterDiskSpaceTask();
var
  ResultCode: Integer;
  TaskName, ThisExePath, CurrentOwnerPath: String;
begin
  // BM3 (2026-08-26 audit) fix for BL6: reproduced live, twice -- uninstalling ANY install under
  // this account used to delete the account's ONE per-account task unconditionally, even when a
  // DIFFERENT install directory currently owned it (e.g. a scratch install's own uninstall
  // deleting gaura's real, unrelated, still-installed task). Fixed: only delete the per-account
  // task if it is CURRENTLY registered against THIS install's own exe path -- if it points
  // somewhere else, some other install owns it now and this uninstall must leave it alone
  // entirely; there is nothing to "re-register" in that case, since the other install's own
  // registration was never touched and is still fully functional.
  TaskName := GetDiskSpaceTaskName();
  ThisExePath := XmlEscape(ExpandConstant('{app}\{#MyAppExeName}'));
  CurrentOwnerPath := GetRegisteredTaskCommandPath(TaskName);
  if (CurrentOwnerPath = '') or (CurrentOwnerPath = ThisExePath) then
    // Empty means the task doesn't exist at all -- this delete is then a harmless no-op, same
    // "don't fail the uninstall over a best-effort cleanup step" posture as before.
    Exec('schtasks.exe', '/delete /tn "' + TaskName + '" /f',
      '', SW_HIDE, ewWaitUntilTerminated, ResultCode);
  // Legacy shared-name cleanup: unchanged from before this fix. This name has no per-install
  // ownership concept left to protect -- BE1 already treats it as pure migration dead weight from
  // pre-BE1 installs, and Windows' own per-task ACL (only the account that created it can delete
  // it) already makes this safe against a different account's uninstall touching it.
  Exec('schtasks.exe', '/delete /tn "' + LegacyDiskSpaceTaskName + '" /f',
    '', SW_HIDE, ewWaitUntilTerminated, ResultCode);
end;

procedure CurStepChanged(CurStep: TSetupStep);
begin
  // ssPostInstall fires after [Files] has finished copying, so {app}\{#MyAppExeName} already
  // exists by the time schtasks' <Command> element is registered against it.
  if CurStep = ssPostInstall then
    RegisterDiskSpaceTask();
end;

// fix/uninstaller-terminate-running-process: a Reclaim server process (the dashboard, or a
// background scan/apply/AI-analysis worker it spawned) holds an OS-level lock on reclaim.exe
// and its loaded DLLs for as long as it's running. Inno's own [Files] removal pass can't clear
// that lock, and used to fail SILENTLY on each locked file rather than aborting the uninstall
// -- Add/Remove Programs correctly reported the app gone (registry entry + shortcuts removed)
// while ~30 program files, still holding real locks, survived on disk. Observed for real: a
// scan-worker process outlived a killed parent and kept writing to data\logs\reclaim.log for
// a full minute after the uninstaller's file-removal pass had already run past it.
//
// InitializeUninstall is the very first thing Inno calls, before any removal begins -- killing
// the process tree here, not at usUninstall's start, means the removal pass itself never has to
// contend with a live process at all.
function InitializeUninstall(): Boolean;
var
  ResultCode: Integer;
begin
  Result := True;
  // /T also kills child processes of the tree (a scan/AI worker spawned via multiprocessing)
  // -- killing only the top-level dashboard process and leaving a worker running is exactly
  // the incident above. /F force-terminates; taskkill exits 0 (killed) or 128 (nothing was
  // running, not an error) -- neither is worth surfacing, and this never needs admin rights to
  // kill a process the current non-elevated user already owns (this installer is always
  // per-user/non-elevated -- see PrivilegesRequired=lowest above).
  Exec('taskkill.exe', '/F /T /IM {#MyAppExeName}', '', SW_HIDE, ewWaitUntilTerminated, ResultCode);
  // Windows releases a terminated process's file handles as part of process teardown, which is
  // prompt but not guaranteed synchronous with taskkill.exe's own exit -- and a freshly-freed
  // reclaim.exe is exactly the kind of file Defender's real-time scanner re-locks transiently
  // right after a process release it (see packaging/RELEASE_RUNBOOK.md's cold-start scan note).
  // A short wait here is cheap insurance against exactly that race.
  Sleep(500);
end;

// Directory enumeration helper for the leftover-file check in CurUninstallStepChanged below --
// True if {app} contains anything other than `data\` (which the [Files] section never lists,
// so Inno's own removal pass never touches it -- see the data-folder-preservation comment
// further down). A non-empty result here means InitializeUninstall's taskkill above didn't
// fully do its job.
function AppDirHasLeftoverFiles(AppDir: String): Boolean;
var
  FindRec: TFindRec;
begin
  Result := False;
  if FindFirst(AppDir + '\*', FindRec) then
  begin
    try
      repeat
        if (FindRec.Name <> '.') and (FindRec.Name <> '..') and (FindRec.Name <> 'data') then
          Result := True;
      until (not FindNext(FindRec)) or Result;
    finally
      FindClose(FindRec);
    end;
  end;
end;

// Reclaim's data (scan index, quarantine vault, mode/apply logs — see the [Icons] comment above
// for why these are relative paths under {app}\data) survives a normal uninstall by default: the
// [Files] section above only ever lists the Nuitka --standalone build output, never {app}\data,
// so Inno Setup's own file-removal pass never touches it. This handler adds the explicit,
// opt-in "also delete my data" step GG's uninstall spec calls for, asked only after the program
// files are already gone (usPostUninstall) so a Cancel/No leaves a fully-working, reinstallable
// data folder behind.
procedure CurUninstallStepChanged(CurUninstallStep: TUninstallStep);
var
  DataDir: String;
  AppDir: String;
  Response: Integer;
begin
  if CurUninstallStep = usUninstall then
    // R5: remove the per-user scheduled task registered by RegisterDiskSpaceTask above. Run at
    // usUninstall (before file removal / the data-folder prompt below) rather than
    // usPostUninstall -- no ordering dependency on either, but this keeps "undo everything this
    // installer registered outside of {app} itself" together as one step, matching
    // InitializeUninstall's own "do the OS-level cleanup first" shape. The [Registry] protocol
    // handler needs no equivalent call here -- Flags: uninsdeletekey in [Registry] above already
    // removes it automatically.
    UnregisterDiskSpaceTask();

  if CurUninstallStep = usPostUninstall then
  begin
    // Defensive verification, not the primary fix (InitializeUninstall's taskkill above is):
    // confirm the removal pass this step follows actually left {app} clean. One retry after a
    // short wait covers a transient re-lock (e.g. Defender); if it's STILL not clean after
    // that, say so plainly instead of leaving silent orphans with no signal at all -- the
    // original bug this whole change fixes.
    AppDir := ExpandConstant('{app}');
    if AppDirHasLeftoverFiles(AppDir) then
    begin
      Sleep(1000);
      if AppDirHasLeftoverFiles(AppDir) and (not UninstallSilent) then
        MsgBox(
          'Reclaim removed most of its program files, but some are still in use by another ' +
          'process and could not be deleted:' + #13#10 + #13#10 + AppDir + #13#10#13#10 +
          'Close any other program using Reclaim (or restart your PC), then delete this ' +
          'folder by hand if it still exists.',
          mbInformation, MB_OK
        );
    end;

    // A silent uninstall (/VERYSILENT or /SILENT) has no one to answer a MsgBox — asking would
    // either hang or auto-answer unpredictably, so silent runs always preserve data/ instead,
    // matching this installer's "leave data behind by default" posture end to end.
    if UninstallSilent then
      Exit;

    DataDir := ExpandConstant('{app}\data');
    if DirExists(DataDir) then
    begin
      Response := MsgBox(
        'Reclaim leaves its data folder behind by default (scan history, the quarantine vault, ' +
        'and logs) so you can reinstall without losing anything -- including any files still ' +
        'held in Reclaim''s vault that you have not restored yet.' + #13#10 + #13#10 +
        'Also delete this data folder now?' + #13#10 + #13#10 +
        'Choose No if you are not sure, or if you still have files in the vault you might want ' +
        'back.',
        mbConfirmation, MB_YESNO or MB_DEFBUTTON2
      );
      if Response = IDYES then
        DelTree(DataDir, True, True, True);
    end;
  end;
end;
